---

version: v1289

nginx:
  image:
    repository: hexletbasics/services-nginx

app:
  image:
    repository: hexletbasics/services-app

# sentry настраивает регистрацию деплоя (см. notify.job.yaml).
sentry:
  image: getsentry/sentry-cli:2
  url: https://sentry.hexlet.io/
  org: hexlet
  environment: production
