FROM nginx:1.23.1

COPY /public /var/www/hexlet-basics/shared/public

COPY services/web-nginx/files/production/nginx.hexlet.basics.conf.template /etc/nginx/conf.d/hexlet-basics.conf.template
COPY services/web-nginx/files/production/gzip.conf /etc/nginx/gzip.conf
COPY services/web-nginx/files/.htpasswd /etc/nginx/.htpasswd
RUN rm -rf /etc/nginx/conf.d/default.conf

COPY services/web-nginx/files/production/docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
