# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `async-http` gem.
# Please instead update this file by running `bin/tapioca gem async-http`.


# pkg:gem/async-http#lib/async/http/protocol/configurable.rb:6
module Async; end

# pkg:gem/async-http#lib/async/http/protocol/configurable.rb:7
module Async::HTTP; end

# pkg:gem/async-http#lib/async/http/body/writable.rb:11
module Async::HTTP::Body; end

# A body which is designed for hijacked server responses - a response which uses a block to read and write the request and response bodies respectively.
#
# pkg:gem/async-http#lib/async/http/body/hijack.rb:15
class Async::HTTP::Body::Hijack < ::Protocol::HTTP::Body::Readable
  # Initialize the hijacked body.
  #
  # @return [Hijack] a new instance of Hijack
  #
  # pkg:gem/async-http#lib/async/http/body/hijack.rb:35
  def initialize(block, input = T.unsafe(nil)); end

  # Invoke the block with the given stream for bidirectional communication.
  #
  # pkg:gem/async-http#lib/async/http/body/hijack.rb:51
  def call(stream); end

  # Has the producer called #finish and has the reader consumed the nil token?
  #
  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/body/hijack.rb:58
  def empty?; end

  # Returns the value of attribute input.
  #
  # pkg:gem/async-http#lib/async/http/body/hijack.rb:55
  def input; end

  # pkg:gem/async-http#lib/async/http/body/hijack.rb:85
  def inspect; end

  # Read the next available chunk.
  #
  # pkg:gem/async-http#lib/async/http/body/hijack.rb:69
  def read; end

  # Whether the body has output ready to be read.
  #
  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/body/hijack.rb:64
  def ready?; end

  # We prefer streaming directly as it's the lowest overhead.
  #
  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/body/hijack.rb:45
  def stream?; end

  # pkg:gem/async-http#lib/async/http/body/hijack.rb:90
  def to_s; end

  class << self
    # Create a response with this hijacked body.
    #
    # pkg:gem/async-http#lib/async/http/body/hijack.rb:21
    def response(request, status, headers, &block); end

    # Wrap a request body with a hijacked body.
    #
    # pkg:gem/async-http#lib/async/http/body/hijack.rb:28
    def wrap(request = T.unsafe(nil), &block); end
  end
end

# Invokes a callback once the body has finished reading.
#
# pkg:gem/async-http#lib/async/http/statistics.rb:40
class Async::HTTP::Body::Statistics < ::Protocol::HTTP::Body::Wrapper
  # Initialize the statistics body wrapper.
  #
  # @return [Statistics] a new instance of Statistics
  #
  # pkg:gem/async-http#lib/async/http/statistics.rb:45
  def initialize(start_time, body, callback); end

  # Close the body and record the end time.
  #
  # pkg:gem/async-http#lib/async/http/statistics.rb:78
  def close(error = T.unsafe(nil)); end

  # Returns the value of attribute end_time.
  #
  # pkg:gem/async-http#lib/async/http/statistics.rb:59
  def end_time; end

  # pkg:gem/async-http#lib/async/http/statistics.rb:71
  def first_chunk_duration; end

  # Returns the value of attribute first_chunk_time.
  #
  # pkg:gem/async-http#lib/async/http/statistics.rb:58
  def first_chunk_time; end

  # pkg:gem/async-http#lib/async/http/statistics.rb:114
  def inspect; end

  # Read the next chunk from the body, tracking timing and bytes sent.
  #
  # pkg:gem/async-http#lib/async/http/statistics.rb:86
  def read; end

  # Returns the value of attribute sent.
  #
  # pkg:gem/async-http#lib/async/http/statistics.rb:61
  def sent; end

  # Returns the value of attribute start_time.
  #
  # pkg:gem/async-http#lib/async/http/statistics.rb:57
  def start_time; end

  # pkg:gem/async-http#lib/async/http/statistics.rb:99
  def to_s; end

  # pkg:gem/async-http#lib/async/http/statistics.rb:64
  def total_duration; end

  private

  # pkg:gem/async-http#lib/async/http/statistics.rb:120
  def complete_statistics(error = T.unsafe(nil)); end

  # pkg:gem/async-http#lib/async/http/statistics.rb:126
  def format_duration(seconds); end
end

# pkg:gem/async-http#lib/async/http/body/writable.rb:12
Async::HTTP::Body::Writable = Protocol::HTTP::Body::Writable

# An HTTP client that manages persistent connections to a specific endpoint, with automatic retries for idempotent requests.
#
# pkg:gem/async-http#lib/async/http/client.rb:21
class Async::HTTP::Client < ::Protocol::HTTP::Methods
  # Provides a robust interface to a server.
  # * If there are no connections, it will create one.
  # * If there are already connections, it will reuse it.
  # * If a request fails, it will retry it up to N times if it was idempotent.
  # The client object will never become unusable. It internally manages persistent connections (or non-persistent connections if that's required).
  #
  # @param authority [String] The default authority to set to requests.
  # @param endpoint [Endpoint] the endpoint to connnect to.
  # @param protocol [Protocol::HTTP1 | Protocol::HTTP2 | Protocol::HTTPS] the protocol to use.
  # @param scheme [String] The default scheme to set to requests.
  # @return [Client] a new instance of Client
  #
  # pkg:gem/async-http#lib/async/http/client.rb:31
  def initialize(endpoint, protocol: T.unsafe(nil), scheme: T.unsafe(nil), authority: T.unsafe(nil), retries: T.unsafe(nil), **options); end

  # pkg:gem/async-http#lib/async/http/client.rb:43
  def as_json(*_arg0, **_arg1, &_arg2); end

  # Returns the value of attribute authority.
  #
  # pkg:gem/async-http#lib/async/http/client.rb:65
  def authority; end

  # Send a request to the remote server, with automatic retries for idempotent requests.
  #
  # pkg:gem/async-http#lib/async/http/client.rb:99
  def call(request); end

  # Close the client and all associated connections.
  #
  # pkg:gem/async-http#lib/async/http/client.rb:88
  def close; end

  # Returns the value of attribute endpoint.
  #
  # pkg:gem/async-http#lib/async/http/client.rb:58
  def endpoint; end

  # pkg:gem/async-http#lib/async/http/client.rb:148
  def inspect; end

  # Returns the value of attribute pool.
  #
  # pkg:gem/async-http#lib/async/http/client.rb:62
  def pool; end

  # Returns the value of attribute protocol.
  #
  # pkg:gem/async-http#lib/async/http/client.rb:59
  def protocol; end

  # Returns the value of attribute retries.
  #
  # pkg:gem/async-http#lib/async/http/client.rb:61
  def retries; end

  # Returns the value of attribute scheme.
  #
  # pkg:gem/async-http#lib/async/http/client.rb:64
  def scheme; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/client.rb:68
  def secure?; end

  # pkg:gem/async-http#lib/async/http/client.rb:54
  def to_json(*_arg0, **_arg1, &_arg2); end

  protected

  # pkg:gem/async-http#lib/async/http/client.rb:162
  def assign_default_tags(tags); end

  # pkg:gem/async-http#lib/async/http/client.rb:167
  def make_pool(**options); end

  # pkg:gem/async-http#lib/async/http/client.rb:154
  def make_response(request, connection, attempt); end

  class << self
    # Open a client and optionally yield it, ensuring it is closed afterwards.
    #
    # pkg:gem/async-http#lib/async/http/client.rb:75
    def open(*arguments, **options, &block); end
  end
end

# pkg:gem/async-http#lib/async/http/client.rb:18
Async::HTTP::DEFAULT_RETRIES = T.let(T.unsafe(nil), Integer)

# Represents a way to connect to a remote HTTP server.
#
# pkg:gem/async-http#lib/async/http/endpoint.rb:23
class Async::HTTP::Endpoint < ::IO::Endpoint::Generic
  # @option alpn_protocols
  # @option hostname
  # @option port
  # @option scheme
  # @option ssl_context
  # @param alpn_protocols [Hash] a customizable set of options
  # @param hostname [Hash] a customizable set of options
  # @param port [Hash] a customizable set of options
  # @param scheme [Hash] a customizable set of options
  # @param ssl_context [Hash] a customizable set of options
  # @raise [ArgumentError]
  # @return [Endpoint] a new instance of Endpoint
  #
  # pkg:gem/async-http#lib/async/http/endpoint.rb:74
  def initialize(url, endpoint = T.unsafe(nil), **options); end

  # pkg:gem/async-http#lib/async/http/endpoint.rb:112
  def address; end

  # pkg:gem/async-http#lib/async/http/endpoint.rb:178
  def alpn_protocols; end

  # pkg:gem/async-http#lib/async/http/endpoint.rb:158
  def authority(ignore_default_port = T.unsafe(nil)); end

  # Bind to the endpoint.
  #
  # pkg:gem/async-http#lib/async/http/endpoint.rb:239
  def bind(*arguments, &block); end

  # Build a suitable endpoint, optionally wrapping in TLS for secure connections.
  #
  # pkg:gem/async-http#lib/async/http/endpoint.rb:212
  def build_endpoint(endpoint = T.unsafe(nil)); end

  # Connect to the endpoint.
  #
  # pkg:gem/async-http#lib/async/http/endpoint.rb:244
  def connect(&block); end

  # pkg:gem/async-http#lib/async/http/endpoint.rb:133
  def default_port; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/endpoint.rb:138
  def default_port?; end

  # Enumerate all resolved endpoints.
  #
  # pkg:gem/async-http#lib/async/http/endpoint.rb:251
  def each; end

  # pkg:gem/async-http#lib/async/http/endpoint.rb:228
  def endpoint; end

  # Set the underlying endpoint, wrapping it as needed.
  #
  # pkg:gem/async-http#lib/async/http/endpoint.rb:234
  def endpoint=(endpoint); end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/endpoint.rb:265
  def eql?(other); end

  # pkg:gem/async-http#lib/async/http/endpoint.rb:270
  def hash; end

  # The hostname is the server we are connecting to:
  #
  # pkg:gem/async-http#lib/async/http/endpoint.rb:148
  def hostname; end

  # pkg:gem/async-http#lib/async/http/endpoint.rb:105
  def inspect; end

  # pkg:gem/async-http#lib/async/http/endpoint.rb:260
  def key; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/endpoint.rb:183
  def localhost?; end

  # Return the path and query components of the given URL.
  #
  # pkg:gem/async-http#lib/async/http/endpoint.rb:167
  def path; end

  # pkg:gem/async-http#lib/async/http/endpoint.rb:143
  def port; end

  # pkg:gem/async-http#lib/async/http/endpoint.rb:122
  def protocol; end

  # pkg:gem/async-http#lib/async/http/endpoint.rb:153
  def scheme; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/endpoint.rb:117
  def secure?; end

  # pkg:gem/async-http#lib/async/http/endpoint.rb:197
  def ssl_context; end

  # We don't try to validate peer certificates when talking to localhost because they would always be self-signed.
  #
  # pkg:gem/async-http#lib/async/http/endpoint.rb:188
  def ssl_verify_mode; end

  # pkg:gem/async-http#lib/async/http/endpoint.rb:100
  def to_s; end

  # pkg:gem/async-http#lib/async/http/endpoint.rb:89
  def to_url; end

  # Returns the value of attribute url.
  #
  # pkg:gem/async-http#lib/async/http/endpoint.rb:109
  def url; end

  protected

  # pkg:gem/async-http#lib/async/http/endpoint.rb:289
  def tcp_endpoint; end

  # pkg:gem/async-http#lib/async/http/endpoint.rb:276
  def tcp_options; end

  class << self
    # Coerce the given object into an endpoint.
    #
    # pkg:gem/async-http#lib/async/http/endpoint.rb:61
    def [](url); end

    # Construct an endpoint with a specified scheme, hostname, optional path, and options.
    #
    # pkg:gem/async-http#lib/async/http/endpoint.rb:47
    def for(scheme, hostname, path = T.unsafe(nil), **options); end

    # Parse a URL string into an endpoint.
    #
    # pkg:gem/async-http#lib/async/http/endpoint.rb:36
    def parse(string, endpoint = T.unsafe(nil), **options); end
  end
end

# pkg:gem/async-http#lib/async/http/endpoint.rb:24
Async::HTTP::Endpoint::SCHEMES = T.let(T.unsafe(nil), Hash)

# A high-level HTTP client for making requests to any URL, managing a pool of persistent connections keyed by host.
#
# pkg:gem/async-http#lib/async/http/internet.rb:17
class Async::HTTP::Internet
  # Initialize the internet client.
  #
  # @return [Internet] a new instance of Internet
  #
  # pkg:gem/async-http#lib/async/http/internet.rb:20
  def initialize(**options); end

  # Make a request to the internet with the given `method` and `url`.
  #
  # If you provide non-frozen headers, they may be mutated.
  #
  # pkg:gem/async-http#lib/async/http/internet.rb:48
  def call(verb, url, *arguments, **options, &block); end

  # Get or create a client for the given endpoint.
  #
  # pkg:gem/async-http#lib/async/http/internet.rb:32
  def client_for(endpoint); end

  # A cache of clients.
  #
  # pkg:gem/async-http#lib/async/http/internet.rb:27
  def clients; end

  # Close all cached clients and release their resources.
  #
  # pkg:gem/async-http#lib/async/http/internet.rb:69
  def close; end

  # pkg:gem/async-http#lib/async/http/internet.rb:78
  def connect(url, *arguments, **options, &block); end

  # pkg:gem/async-http#lib/async/http/internet.rb:78
  def delete(url, *arguments, **options, &block); end

  # pkg:gem/async-http#lib/async/http/internet.rb:78
  def get(url, *arguments, **options, &block); end

  # pkg:gem/async-http#lib/async/http/internet.rb:78
  def head(url, *arguments, **options, &block); end

  # pkg:gem/async-http#lib/async/http/internet.rb:78
  def options(url, *arguments, **options, &block); end

  # pkg:gem/async-http#lib/async/http/internet.rb:78
  def patch(url, *arguments, **options, &block); end

  # pkg:gem/async-http#lib/async/http/internet.rb:78
  def post(url, *arguments, **options, &block); end

  # pkg:gem/async-http#lib/async/http/internet.rb:78
  def put(url, *arguments, **options, &block); end

  # pkg:gem/async-http#lib/async/http/internet.rb:78
  def trace(url, *arguments, **options, &block); end

  protected

  # pkg:gem/async-http#lib/async/http/internet.rb:91
  def host_key(endpoint); end

  # pkg:gem/async-http#lib/async/http/internet.rb:85
  def make_client(endpoint); end
end

# A protocol specifies a way in which to communicate with a remote peer.
#
# pkg:gem/async-http#lib/async/http/protocol/configurable.rb:8
module Async::HTTP::Protocol; end

# Provides a `new` method that creates a {Configured} wrapper, allowing protocols to be instantiated with custom options.
#
# pkg:gem/async-http#lib/async/http/protocol/configurable.rb:48
module Async::HTTP::Protocol::Configurable
  # Create a new {Configured} instance wrapping this protocol with the given options.
  #
  # pkg:gem/async-http#lib/async/http/protocol/configurable.rb:52
  def new(**options); end
end

# A protocol wrapper that forwards pre-configured options to client and server creation.
#
# pkg:gem/async-http#lib/async/http/protocol/configurable.rb:10
class Async::HTTP::Protocol::Configured
  # Initialize with a protocol and options.
  #
  # @return [Configured] a new instance of Configured
  #
  # pkg:gem/async-http#lib/async/http/protocol/configurable.rb:14
  def initialize(protocol, **options); end

  # Create a client connection using the configured protocol options.
  #
  # pkg:gem/async-http#lib/async/http/protocol/configurable.rb:28
  def client(peer, **options); end

  # pkg:gem/async-http#lib/async/http/protocol/configurable.rb:42
  def names; end

  # Returns the value of attribute options.
  #
  # pkg:gem/async-http#lib/async/http/protocol/configurable.rb:23
  def options; end

  # Returns the value of attribute protocol.
  #
  # pkg:gem/async-http#lib/async/http/protocol/configurable.rb:20
  def protocol; end

  # Create a server connection using the configured protocol options.
  #
  # pkg:gem/async-http#lib/async/http/protocol/configurable.rb:36
  def server(peer, **options); end
end

# This module provides a default instance of the protocol, which can be used to create clients and servers. The name is a play on "Default" + "Singleton".
#
# pkg:gem/async-http#lib/async/http/protocol/defaulton.rb:10
module Async::HTTP::Protocol::Defaulton
  # Create a client for an outbound connection, using the default instance.
  #
  # pkg:gem/async-http#lib/async/http/protocol/defaulton.rb:18
  def client(peer, **options); end

  # Returns the value of attribute default.
  #
  # pkg:gem/async-http#lib/async/http/protocol/defaulton.rb:15
  def default; end

  # Sets the attribute default
  #
  # @param value the value to set the attribute default to.
  #
  # pkg:gem/async-http#lib/async/http/protocol/defaulton.rb:15
  def default=(_arg0); end

  # pkg:gem/async-http#lib/async/http/protocol/defaulton.rb:28
  def names; end

  # Create a server for an inbound connection, using the default instance.
  #
  # pkg:gem/async-http#lib/async/http/protocol/defaulton.rb:23
  def server(peer, **options); end

  class << self
    # @private
    #
    # pkg:gem/async-http#lib/async/http/protocol/defaulton.rb:11
    def extended(base); end
  end
end

# HTTP is an http:// server that auto-selects HTTP/1.1 or HTTP/2 by detecting the HTTP/2 connection preface.
#
# pkg:gem/async-http#lib/async/http/protocol/http.rb:16
class Async::HTTP::Protocol::HTTP
  extend ::Async::HTTP::Protocol::Defaulton

  # Create a new HTTP protocol instance.
  #
  # @return [HTTP] a new instance of HTTP
  #
  # pkg:gem/async-http#lib/async/http/protocol/http.rb:24
  def initialize(http1: T.unsafe(nil), http2: T.unsafe(nil)); end

  # Create a client for an outbound connection. Defaults to HTTP/1 for plaintext connections.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http.rb:56
  def client(peer, **options); end

  # Determine if the inbound connection is HTTP/1 or HTTP/2.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http.rb:33
  def protocol_for(stream); end

  # Create a server for an inbound connection. Able to detect HTTP1 and HTTP2.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http.rb:66
  def server(peer, **options); end
end

# Provides HTTP/1.0 and HTTP/1.1 client and server implementations.
#
# pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:11
module Async::HTTP::Protocol::HTTP1
  extend ::Async::HTTP::Protocol::Configurable

  class << self
    # @return [Boolean]
    #
    # pkg:gem/async-http#lib/async/http/protocol/http1.rb:24
    def bidirectional?; end

    # Create a client for an outbound connection.
    #
    # pkg:gem/async-http#lib/async/http/protocol/http1.rb:37
    def client(peer, **options); end

    # pkg:gem/async-http#lib/async/http/protocol/http1.rb:54
    def names; end

    # Create a server for an inbound connection.
    #
    # pkg:gem/async-http#lib/async/http/protocol/http1.rb:47
    def server(peer, **options); end

    # @return [Boolean]
    #
    # pkg:gem/async-http#lib/async/http/protocol/http1.rb:29
    def trailer?; end
  end
end

# Provides an HTTP/1.0 client and server protocol implementation.
#
# pkg:gem/async-http#lib/async/http/protocol/http10.rb:13
module Async::HTTP::Protocol::HTTP10
  extend ::Async::HTTP::Protocol::Configurable

  class << self
    # @return [Boolean]
    #
    # pkg:gem/async-http#lib/async/http/protocol/http10.rb:19
    def bidirectional?; end

    # Create a client for an outbound connection.
    #
    # pkg:gem/async-http#lib/async/http/protocol/http10.rb:32
    def client(peer, **options); end

    # pkg:gem/async-http#lib/async/http/protocol/http10.rb:49
    def names; end

    # Create a server for an inbound connection.
    #
    # pkg:gem/async-http#lib/async/http/protocol/http10.rb:42
    def server(peer, **options); end

    # @return [Boolean]
    #
    # pkg:gem/async-http#lib/async/http/protocol/http10.rb:24
    def trailer?; end
  end
end

# pkg:gem/async-http#lib/async/http/protocol/http10.rb:16
Async::HTTP::Protocol::HTTP10::VERSION = T.let(T.unsafe(nil), String)

# Provides an HTTP/1.1 client and server protocol implementation.
#
# pkg:gem/async-http#lib/async/http/protocol/http11.rb:14
module Async::HTTP::Protocol::HTTP11
  extend ::Async::HTTP::Protocol::Configurable

  class << self
    # @return [Boolean]
    #
    # pkg:gem/async-http#lib/async/http/protocol/http11.rb:20
    def bidirectional?; end

    # Create a client for an outbound connection.
    #
    # pkg:gem/async-http#lib/async/http/protocol/http11.rb:33
    def client(peer, **options); end

    # pkg:gem/async-http#lib/async/http/protocol/http11.rb:50
    def names; end

    # Create a server for an inbound connection.
    #
    # pkg:gem/async-http#lib/async/http/protocol/http11.rb:43
    def server(peer, **options); end

    # @return [Boolean]
    #
    # pkg:gem/async-http#lib/async/http/protocol/http11.rb:25
    def trailer?; end
  end
end

# pkg:gem/async-http#lib/async/http/protocol/http11.rb:17
Async::HTTP::Protocol::HTTP11::VERSION = T.let(T.unsafe(nil), String)

# An HTTP/1 client connection that sends requests and reads responses.
#
# pkg:gem/async-http#lib/async/http/protocol/http1/client.rb:13
class Async::HTTP::Protocol::HTTP1::Client < ::Async::HTTP::Protocol::HTTP1::Connection
  # Initialize the HTTP/1 client connection.
  #
  # @return [Client] a new instance of Client
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/client.rb:15
  def initialize(*_arg0, **_arg1, &_arg2); end

  # Used by the client to send requests to the remote server.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/client.rb:35
  def call(request, task: T.unsafe(nil)); end

  # Called when the connection is closed, releasing it back to the pool.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/client.rb:24
  def closed(error = T.unsafe(nil)); end

  # Returns the value of attribute pool.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/client.rb:21
  def pool; end

  # Sets the attribute pool
  #
  # @param value the value to set the attribute pool to.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/client.rb:21
  def pool=(_arg0); end
end

# An HTTP/1 connection that wraps an IO stream with version and state tracking.
#
# pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:17
class Async::HTTP::Protocol::HTTP1::Connection < ::Protocol::HTTP1::Connection
  # Initialize the connection with an IO stream and HTTP version.
  #
  # @return [Connection] a new instance of Connection
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:22
  def initialize(stream, version, **options); end

  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:35
  def as_json(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:64
  def concurrency; end

  # Returns the value of attribute count.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:61
  def count; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:47
  def http1?; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:52
  def http2?; end

  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:57
  def peer; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:74
  def reusable?; end

  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:40
  def to_json(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:30
  def to_s; end

  # Returns the value of attribute version.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:44
  def version; end

  # Can we use this connection to make requests?
  #
  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:69
  def viable?; end
end

# Keeps track of whether a body is being read, and if so, waits for it to be closed.
#
# pkg:gem/async-http#lib/async/http/protocol/http1/finishable.rb:14
class Async::HTTP::Protocol::HTTP1::Finishable < ::Protocol::HTTP::Body::Wrapper
  # Initialize the finishable wrapper.
  #
  # @return [Finishable] a new instance of Finishable
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/finishable.rb:17
  def initialize(body); end

  # Close the body and signal any waiting tasks.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/finishable.rb:40
  def close(error = T.unsafe(nil)); end

  # pkg:gem/async-http#lib/async/http/protocol/http1/finishable.rb:64
  def inspect; end

  # Read the next chunk from the body.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/finishable.rb:33
  def read; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/finishable.rb:27
  def reading?; end

  # Wait for the body to be fully consumed or discard it.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/finishable.rb:51
  def wait(persistent = T.unsafe(nil)); end
end

# An incoming HTTP/1 request parsed from the connection.
#
# pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:13
class Async::HTTP::Protocol::HTTP1::Request < ::Async::HTTP::Protocol::Request
  # Initialize the request from the parsed components.
  #
  # @return [Request] a new instance of Request
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:61
  def initialize(connection, scheme, authority, method, path, version, headers, body); end

  # pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:71
  def connection; end

  # Hijack the underlying connection for bidirectional communication.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:81
  def hijack!; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:76
  def hijack?; end

  # Write an interim (1xx) response to the client.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:88
  def write_interim_response(status, headers = T.unsafe(nil)); end

  class << self
    # Read and parse the next request from the connection.
    #
    # pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:32
    def read(connection); end

    # Check whether the given request target is a valid path.
    #
    # @return [Boolean]
    #
    # pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:17
    def valid_path?(target); end
  end
end

# pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:50
Async::HTTP::Protocol::HTTP1::Request::UPGRADE = T.let(T.unsafe(nil), String)

# pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:27
Async::HTTP::Protocol::HTTP1::Request::URI_PATTERN = T.let(T.unsafe(nil), Regexp)

# An HTTP/1 response received from a server.
#
# pkg:gem/async-http#lib/async/http/protocol/http1/response.rb:14
class Async::HTTP::Protocol::HTTP1::Response < ::Async::HTTP::Protocol::Response
  # @return [Response] a new instance of Response
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/response.rb:37
  def initialize(connection, version, status, reason, headers, body); end

  # pkg:gem/async-http#lib/async/http/protocol/http1/response.rb:58
  def connection; end

  # Hijack the underlying connection for bidirectional communication.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/response.rb:68
  def hijack!; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/response.rb:63
  def hijack?; end

  # Assign the connection pool, releasing the connection if it is already idle or closed.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/response.rb:49
  def pool=(pool); end

  # Returns the value of attribute reason.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/response.rb:34
  def reason; end

  class << self
    # Read the response from the connection, handling interim responses.
    #
    # pkg:gem/async-http#lib/async/http/protocol/http1/response.rb:19
    def read(connection, request); end
  end
end

# pkg:gem/async-http#lib/async/http/protocol/http1/response.rb:31
Async::HTTP::Protocol::HTTP1::Response::UPGRADE = T.let(T.unsafe(nil), String)

# An HTTP/1 server connection that receives requests and sends responses.
#
# pkg:gem/async-http#lib/async/http/protocol/http1/server.rb:20
class Async::HTTP::Protocol::HTTP1::Server < ::Async::HTTP::Protocol::HTTP1::Connection
  # Initialize the HTTP/1 server connection.
  #
  # @return [Server] a new instance of Server
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/server.rb:22
  def initialize(*_arg0, **_arg1, &_arg2); end

  # Called when the connection is closed, signalling any waiting tasks.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/server.rb:29
  def closed(error = T.unsafe(nil)); end

  # Server loop.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/server.rb:70
  def each(task: T.unsafe(nil)); end

  # Write a failure response with the given status code.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/server.rb:37
  def fail_request(status); end

  # Read the next incoming request from the connection.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/server.rb:48
  def next_request; end
end

# pkg:gem/async-http#lib/async/http/protocol/http1.rb:21
Async::HTTP::Protocol::HTTP1::VERSION = T.let(T.unsafe(nil), String)

# Provides an HTTP/2 client and server protocol implementation.
#
# pkg:gem/async-http#lib/async/http/protocol/http2/input.rb:11
module Async::HTTP::Protocol::HTTP2
  extend ::Async::HTTP::Protocol::Configurable

  class << self
    # @return [Boolean]
    #
    # pkg:gem/async-http#lib/async/http/protocol/http2.rb:24
    def bidirectional?; end

    # Create a client for an outbound connection.
    #
    # pkg:gem/async-http#lib/async/http/protocol/http2.rb:55
    def client(peer, settings: T.unsafe(nil)); end

    # pkg:gem/async-http#lib/async/http/protocol/http2.rb:80
    def names; end

    # Create a server for an inbound connection.
    #
    # pkg:gem/async-http#lib/async/http/protocol/http2.rb:69
    def server(peer, settings: T.unsafe(nil)); end

    # @return [Boolean]
    #
    # pkg:gem/async-http#lib/async/http/protocol/http2.rb:29
    def trailer?; end
  end
end

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:21
Async::HTTP::Protocol::HTTP2::AUTHORITY = T.let(T.unsafe(nil), String)

# The default settings for the client.
#
# pkg:gem/async-http#lib/async/http/protocol/http2.rb:34
Async::HTTP::Protocol::HTTP2::CLIENT_SETTINGS = T.let(T.unsafe(nil), Hash)

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:26
Async::HTTP::Protocol::HTTP2::CONNECTION = T.let(T.unsafe(nil), String)

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:25
Async::HTTP::Protocol::HTTP2::CONTENT_LENGTH = T.let(T.unsafe(nil), String)

# An HTTP/2 client connection that sends requests and reads responses.
#
# pkg:gem/async-http#lib/async/http/protocol/http2/client.rb:16
class Async::HTTP::Protocol::HTTP2::Client < ::Protocol::HTTP2::Client
  include ::Async::HTTP::Protocol::HTTP2::Connection

  # Initialize the HTTP/2 client with an IO stream.
  #
  # @return [Client] a new instance of Client
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/client.rb:21
  def initialize(stream); end

  # Used by the client to send requests to the remote server.
  #
  # @raise [::Protocol::HTTP2::Error]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/client.rb:36
  def call(request); end

  # Create a new response stream for the next request.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/client.rb:31
  def create_response; end

  # Wait for the response headers to arrive.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/client.rb:55
  def read_response(response); end

  # Write a request to the remote server via the given response stream.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/client.rb:49
  def write_request(response, request); end
end

# Provides shared connection behaviour for HTTP/2 client and server connections.
#
# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:30
module Async::HTTP::Protocol::HTTP2::Connection
  # Initialize the connection state.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:32
  def initialize(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:53
  def as_json(*_arg0, **_arg1, &_arg2); end

  # Close the connection and stop the background reader.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:80
  def close(error = T.unsafe(nil)); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:129
  def concurrency; end

  # Returns the value of attribute count.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:126
  def count; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:65
  def http1?; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:70
  def http2?; end

  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:122
  def peer; end

  # Returns the value of attribute promises.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:119
  def promises; end

  # Start a transient background task that reads frames from the connection.
  #
  # @raise [RuntimeError]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:92
  def read_in_background(parent: T.unsafe(nil)); end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:139
  def reusable?; end

  # Start the background reader task if it is not already running.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:75
  def start_connection; end

  # Returns the value of attribute stream.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:62
  def stream; end

  # Synchronize write access to the connection.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:43
  def synchronize(&block); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:58
  def to_json(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:48
  def to_s; end

  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:144
  def version; end

  # Can we use this connection to make requests?
  #
  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:134
  def viable?; end
end

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:17
Async::HTTP::Protocol::HTTP2::HTTPS = T.let(T.unsafe(nil), String)

# A writable body which requests window updates when data is read from it.
#
# pkg:gem/async-http#lib/async/http/protocol/http2/input.rb:13
class Async::HTTP::Protocol::HTTP2::Input < ::Protocol::HTTP::Body::Writable
  # Initialize the input body.
  #
  # @return [Input] a new instance of Input
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/input.rb:17
  def initialize(stream, length); end

  # Read the next chunk of data, requesting window updates as needed.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/input.rb:26
  def read; end
end

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:19
Async::HTTP::Protocol::HTTP2::METHOD = T.let(T.unsafe(nil), String)

# Writes body data to an HTTP/2 stream, respecting flow control windows.
#
# pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:13
class Async::HTTP::Protocol::HTTP2::Output
  # Initialize the output handler.
  #
  # @return [Output] a new instance of Output
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:18
  def initialize(stream, body, trailer = T.unsafe(nil)); end

  # This method should only be called from within the context of the output task.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:86
  def close(error = T.unsafe(nil)); end

  # Finish writing to the stream.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:78
  def close_write(error = T.unsafe(nil)); end

  # Start an asynchronous task to write the body to the stream.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:32
  def start(parent: T.unsafe(nil)); end

  # This method should only be called from within the context of the HTTP/2 stream.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:92
  def stop(error); end

  # Returns the value of attribute trailer.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:29
  def trailer; end

  # Signal that the flow control window has been updated.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:45
  def window_updated(size); end

  # Write a chunk of data to the HTTP/2 stream, respecting flow control.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:55
  def write(chunk); end

  private

  # Reads chunks from the given body and writes them to the stream as fast as possible.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:114
  def passthrough(task); end

  # Send `maximum_size` bytes of data using the specified `stream`. If the buffer has no more chunks, `END_STREAM` will be sent on the final chunk.
  #
  # @param maximum_size [Integer] send up to this many bytes of data.
  # @param stream [Stream] the stream to use for sending data frames.
  # @return [String, nil] any data that could not be written.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:140
  def send_data(chunk, maximum_size); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:101
  def stream(task); end
end

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:20
Async::HTTP::Protocol::HTTP2::PATH = T.let(T.unsafe(nil), String)

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:23
Async::HTTP::Protocol::HTTP2::PROTOCOL = T.let(T.unsafe(nil), String)

# Typically used on the server side to represent an incoming request, and write the response.
#
# pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:14
class Async::HTTP::Protocol::HTTP2::Request < ::Async::HTTP::Protocol::Request
  # Initialize the request from an HTTP/2 stream.
  #
  # @return [Request] a new instance of Request
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:98
  def initialize(stream); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:107
  def connection; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:117
  def hijack?; end

  # Send a response back to the client via the HTTP/2 stream.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:127
  def send_response(response); end

  # Returns the value of attribute stream.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:104
  def stream; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:112
  def valid?; end

  # Write an interim (1xx) response to the client.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:163
  def write_interim_response(status, headers = T.unsafe(nil)); end
end

# pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:121
Async::HTTP::Protocol::HTTP2::Request::NO_RESPONSE = T.let(T.unsafe(nil), Array)

# Represents the HTTP/2 stream associated with an incoming server-side request.
#
# pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:16
class Async::HTTP::Protocol::HTTP2::Request::Stream < ::Async::HTTP::Protocol::HTTP2::Stream
  # Initialize the request stream.
  #
  # @return [Stream] a new instance of Stream
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:18
  def initialize(*_arg0); end

  # Called when the stream is closed.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:89
  def closed(error); end

  # Process the initial headers received from the client and construct the request.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:30
  def receive_initial_headers(headers, end_stream); end

  # Returns the value of attribute request.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:25
  def request; end
end

# Typically used on the client side for writing a request and reading the incoming response.
#
# pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:14
class Async::HTTP::Protocol::HTTP2::Response < ::Async::HTTP::Protocol::Response
  # Initialize the response from an HTTP/2 stream.
  #
  # @return [Response] a new instance of Response
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:144
  def initialize(stream); end

  # Build a request object from push promise headers.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:189
  def build_request(headers); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:167
  def connection; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:177
  def head?; end

  # Assign the connection pool, releasing the connection when the stream is closed.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:156
  def pool=(pool); end

  # Returns the value of attribute request.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:152
  def request; end

  # Send a request and read it into this response.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:222
  def send_request(request); end

  # Returns the value of attribute stream.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:151
  def stream; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:182
  def valid?; end

  # Wait for the response headers to be received.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:172
  def wait; end
end

# Represents the HTTP/2 stream associated with an outgoing client-side response.
#
# pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:16
class Async::HTTP::Protocol::HTTP2::Response::Stream < ::Async::HTTP::Protocol::HTTP2::Stream
  # Initialize the response stream.
  #
  # @return [Stream] a new instance of Stream
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:18
  def initialize(*_arg0); end

  # Handle a push promise stream from the server.
  #
  # @raise [ProtocolError]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:42
  def accept_push_promise_stream(promised_stream_id, headers); end

  # Called when the stream is closed.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:129
  def closed(error); end

  # Notify anyone waiting on the response headers to be received (or failure).
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:110
  def notify!; end

  # This should be invoked from the background reader, and notifies the task waiting for the headers that we are done.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:47
  def receive_initial_headers(headers, end_stream); end

  # Process interim (1xx) response headers.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:99
  def receive_interim_headers(status, headers); end

  # Returns the value of attribute response.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:27
  def response; end

  # Wait for the headers to be received or for stream reset.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:118
  def wait; end

  # Wait for the response headers and return the response body.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:31
  def wait_for_input; end
end

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:18
Async::HTTP::Protocol::HTTP2::SCHEME = T.let(T.unsafe(nil), String)

# The default settings for the server.
#
# pkg:gem/async-http#lib/async/http/protocol/http2.rb:42
Async::HTTP::Protocol::HTTP2::SERVER_SETTINGS = T.let(T.unsafe(nil), Hash)

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:22
Async::HTTP::Protocol::HTTP2::STATUS = T.let(T.unsafe(nil), String)

# An HTTP/2 server connection that receives requests and sends responses.
#
# pkg:gem/async-http#lib/async/http/protocol/http2/server.rb:16
class Async::HTTP::Protocol::HTTP2::Server < ::Protocol::HTTP2::Server
  include ::Async::HTTP::Protocol::HTTP2::Connection

  # Initialize the HTTP/2 server with an IO stream.
  #
  # @return [Server] a new instance of Server
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/server.rb:21
  def initialize(stream); end

  # Accept a new stream from a client.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/server.rb:36
  def accept_stream(stream_id); end

  # Close the server connection and stop accepting requests.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/server.rb:43
  def close(error = T.unsafe(nil)); end

  # Enumerate incoming requests, yielding each one for processing.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/server.rb:56
  def each(task: T.unsafe(nil)); end

  # Returns the value of attribute requests.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/server.rb:32
  def requests; end
end

# An HTTP/2 stream that manages headers, input data, and output data for a single request/response exchange.
#
# pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:18
class Async::HTTP::Protocol::HTTP2::Stream < ::Protocol::HTTP2::Stream
  # Initialize the stream state.
  #
  # @return [Stream] a new instance of Stream
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:20
  def initialize(*_arg0); end

  # Add a header to the stream, validating against HTTP/2 constraints.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:44
  def add_header(key, value, trailer: T.unsafe(nil)); end

  # When the stream transitions to the closed state, this method is called. There are roughly two ways this can happen:
  # - A frame is received which causes this stream to enter the closed state. This method will be invoked from the background reader task.
  # - A frame is sent which causes this stream to enter the closed state. This method will be invoked from that task.
  # While the input stream is relatively straight forward, the output stream can trigger the second case above
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:176
  def closed(error); end

  # Called when the output terminates normally.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:142
  def finish_output(error = T.unsafe(nil)); end

  # Returns the value of attribute headers.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:35
  def headers; end

  # Sets the attribute headers
  #
  # @param value the value to set the attribute headers to.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:35
  def headers=(_arg0); end

  # Returns the value of attribute input.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:39
  def input; end

  # Returns the value of attribute pool.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:37
  def pool; end

  # Sets the attribute pool
  #
  # @param value the value to set the attribute pool to.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:37
  def pool=(_arg0); end

  # Prepare the input stream which will be used for incoming data frames.
  #
  # @return [Input] the input body.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:94
  def prepare_input(length); end

  # Process an incoming DATA frame and write it to the input body.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:114
  def process_data(frame); end

  # Process an incoming HEADERS frame, dispatching to initial or trailing header handling.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:67
  def process_headers(frame); end

  # Process trailing headers received after the body.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:59
  def receive_trailing_headers(headers, end_stream); end

  # Set the body and begin sending it.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:135
  def send_body(body, trailer = T.unsafe(nil)); end

  # Update the local flow control window after receiving data.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:104
  def update_local_window(frame); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:88
  def wait_for_input; end

  # Called when the flow control window is updated.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:164
  def window_updated(size); end
end

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:27
Async::HTTP::Protocol::HTTP2::TRAILER = T.let(T.unsafe(nil), String)

# pkg:gem/async-http#lib/async/http/protocol/http2.rb:21
Async::HTTP::Protocol::HTTP2::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/async-http#lib/async/http/protocol/http.rb:17
Async::HTTP::Protocol::HTTP::HTTP2_PREFACE = T.let(T.unsafe(nil), String)

# pkg:gem/async-http#lib/async/http/protocol/http.rb:18
Async::HTTP::Protocol::HTTP::HTTP2_PREFACE_SIZE = T.let(T.unsafe(nil), Integer)

# A server that supports both HTTP1.0 and HTTP1.1 semantics by detecting the version of the request.
#
# pkg:gem/async-http#lib/async/http/protocol/https.rb:17
class Async::HTTP::Protocol::HTTPS
  extend ::Async::HTTP::Protocol::Defaulton

  # Initialize the HTTPS protocol negotiator.
  #
  # @return [HTTPS] a new instance of HTTPS
  #
  # pkg:gem/async-http#lib/async/http/protocol/https.rb:29
  def initialize(handlers = T.unsafe(nil), **options); end

  # Register a protocol handler for a given ALPN protocol name.
  #
  # pkg:gem/async-http#lib/async/http/protocol/https.rb:38
  def add(name, protocol, **options); end

  # Create a client for an outbound connection.
  #
  # pkg:gem/async-http#lib/async/http/protocol/https.rb:66
  def client(peer, **options); end

  # pkg:gem/async-http#lib/async/http/protocol/https.rb:85
  def names; end

  # Determine the protocol of the peer and return the appropriate protocol class.
  #
  # Use TLS Application Layer Protocol Negotiation (ALPN) to determine the protocol.
  #
  # pkg:gem/async-http#lib/async/http/protocol/https.rb:49
  def protocol_for(peer); end

  # Create a server for an inbound connection.
  #
  # pkg:gem/async-http#lib/async/http/protocol/https.rb:77
  def server(peer, **options); end
end

# The protocol classes for each supported protocol.
#
# pkg:gem/async-http#lib/async/http/protocol/https.rb:19
Async::HTTP::Protocol::HTTPS::HANDLERS = T.let(T.unsafe(nil), Hash)

# An incoming HTTP request generated by server protocol implementations.
#
# pkg:gem/async-http#lib/async/http/protocol/request.rb:15
class Async::HTTP::Protocol::Request < ::Protocol::HTTP::Request
  # pkg:gem/async-http#lib/async/http/protocol/request.rb:17
  def connection; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/request.rb:22
  def hijack?; end

  # pkg:gem/async-http#lib/async/http/protocol/request.rb:43
  def inspect; end

  # pkg:gem/async-http#lib/async/http/protocol/request.rb:33
  def peer; end

  # pkg:gem/async-http#lib/async/http/protocol/request.rb:38
  def remote_address; end

  # Write an interim (1xx) response back to the client.
  #
  # pkg:gem/async-http#lib/async/http/protocol/request.rb:29
  def write_interim_response(status, headers = T.unsafe(nil)); end
end

# An HTTP response received from a server via client protocol implementations.
#
# pkg:gem/async-http#lib/async/http/protocol/response.rb:14
class Async::HTTP::Protocol::Response < ::Protocol::HTTP::Response
  # pkg:gem/async-http#lib/async/http/protocol/response.rb:16
  def connection; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/response.rb:21
  def hijack?; end

  # pkg:gem/async-http#lib/async/http/protocol/response.rb:36
  def inspect; end

  # pkg:gem/async-http#lib/async/http/protocol/response.rb:26
  def peer; end

  # pkg:gem/async-http#lib/async/http/protocol/response.rb:31
  def remote_address; end
end

# An HTTP server that accepts connections on a specific endpoint and dispatches requests to an application handler.
#
# pkg:gem/async-http#lib/async/http/server.rb:16
class Async::HTTP::Server < ::Protocol::HTTP::Middleware
  # Initialize the server with an application handler and endpoint.
  #
  # @return [Server] a new instance of Server
  #
  # pkg:gem/async-http#lib/async/http/server.rb:29
  def initialize(app, endpoint, protocol: T.unsafe(nil), scheme: T.unsafe(nil)); end

  # Accept an incoming connection and process requests.
  #
  # pkg:gem/async-http#lib/async/http/server.rb:58
  def accept(peer, address, task: T.unsafe(nil)); end

  # pkg:gem/async-http#lib/async/http/server.rb:38
  def as_json(*_arg0, **_arg1, &_arg2); end

  # Returns the value of attribute endpoint.
  #
  # pkg:gem/async-http#lib/async/http/server.rb:51
  def endpoint; end

  # Returns the value of attribute protocol.
  #
  # pkg:gem/async-http#lib/async/http/server.rb:52
  def protocol; end

  # pkg:gem/async-http#lib/async/http/server.rb:78
  def run; end

  # Returns the value of attribute scheme.
  #
  # pkg:gem/async-http#lib/async/http/server.rb:53
  def scheme; end

  # pkg:gem/async-http#lib/async/http/server.rb:47
  def to_json(*_arg0, **_arg1, &_arg2); end

  class << self
    # Create a server using a block as the application handler.
    #
    # pkg:gem/async-http#lib/async/http/server.rb:20
    def for(*arguments, **options, &block); end
  end
end

# Tracks response timing statistics including time to first byte and total duration.
#
# pkg:gem/async-http#lib/async/http/statistics.rb:13
class Async::HTTP::Statistics
  # Initialize the statistics tracker.
  #
  # @return [Statistics] a new instance of Statistics
  #
  # pkg:gem/async-http#lib/async/http/statistics.rb:22
  def initialize(start_time); end

  # Wrap a response body with a statistics-collecting wrapper.
  #
  # pkg:gem/async-http#lib/async/http/statistics.rb:29
  def wrap(response, &block); end

  class << self
    # Start tracking statistics from the current time.
    #
    # pkg:gem/async-http#lib/async/http/statistics.rb:16
    def start; end
  end
end

# pkg:gem/async-http#lib/async/http/version.rb:10
Async::HTTP::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/async-http#lib/async/http/body/writable.rb:12
class Protocol::HTTP::Body::Writable < ::Protocol::HTTP::Body::Readable; end
