---

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: "{{ include "codebasics.fullname" . }}-gateway"
  labels:
    {{- include "codebasics.labels" . | nindent 4 }}
spec:
  gatewayClassName: "{{ .Values.gatewayClassName }}"
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        certificateRefs:
          - group: gwin.yandex.cloud
            kind: YCCertificate
            name: "{{ include "codebasics.fullname" . }}-yc-certificate"
  addresses:
    - type: "{{ .Values.gatewayAddressType }}"
      value: "{{ .Values.gatewayAddressValue }}"
