---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "{{ include "codebasics.fullname" . }}-main-httproute"
  labels:
    {{- include "codebasics.labels" . | nindent 4 }}
spec:
  hostnames:
    - "{{ .Values.primaryHost }}"
    - "{{ .Values.wildcardHost }}"
  parentRefs:
    - name: "{{ include "codebasics.fullname" . }}-gateway"
      sectionName: https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /ru/api/lessons/
      backendRefs:
        - name: "{{ include "codebasics.fullname" . }}-web-check-service"
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /api/lessons/
      backendRefs:
        - name: "{{ include "codebasics.fullname" . }}-web-check-service"
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: "{{ include "codebasics.fullname" . }}-web-service"
          port: 80
