{{- if .Values.networkPolicyEnabled }}
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ include "codebasics.fullname" . }}-web-network-policy"
  labels:
    {{- include "codebasics.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "codebasics.name" . }}"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
          - "web"
          - "web-check"
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
{{- end }}
