apiVersion: v1
kind: Secret
metadata:
  name: "codebasics-environment-secrets"
  labels:
    {{- include "codebasics.labels" . | nindent 4 }}
type: Opaque
{{- if gt (len .Values.appEnv) 0 }}
data:
  {{- range $key, $value := .Values.appEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- else }}
data: {}
{{- end }}
