---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ include "codebasics.fullname" . }}-prepare-users-code-path-pod"
  labels:
    {{- include "codebasics.labels" . | nindent 4 }}
    app.kubernetes.io/component: "prepare-users-code-path"

spec:
  selector:
    matchLabels:
      {{- include "codebasics.selectorLabels" (dict "context" . "component" "prepare-users-code-path") | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "codebasics.labels" . | nindent 8 }}
        app.kubernetes.io/component: "prepare-users-code-path"

    spec:
      nodeSelector:
        group: "{{ .Release.Namespace }}"

      volumes:
        - name: users-code-path
          hostPath:
            path: /tmp/hexlet-basics
            type: DirectoryOrCreate

      initContainers:
        - name: volume-permissions
          image: busybox
          command: ['sh', '-c', 'chown -R 1000:1000 /tmp/hexlet-basics']
          volumeMounts:
            - mountPath: /tmp/hexlet-basics
              name: users-code-path

      containers:
        - name: pause
          image: registry.k8s.io/pause:3.10.1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
