---

apiVersion: gwin.yandex.cloud/v1
kind: YCCertificate
metadata:
  name: "{{ include "codebasics.fullname" . }}-yc-certificate"
  labels:
    {{- include "codebasics.labels" . | nindent 4 }}
spec:
  certificateRef:
    certificateID: "{{ .Values.gatewayCertificateId }}"
