---

# inherit_mode:
#   merge:
#     - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.0
  TargetRailsVersion: 7
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'

# RSpec:
#   Patterns:
#     - 'test/factories'

require:
  # https://github.com/Shopify/rubocop-sorbet
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance
  - rubocop-rake

Rails:
  Enabled: true

Style/HashSyntax:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false

Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/BlockLength:
  # Max: 100
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Rake/Desc:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

# Гард штука хорошая, но часто логика именно такая:
# Если что-то то делаем так и это не гард.
# Инвертирование условия делает понимание хуже.
Style/GuardClause:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

# Выключил временно, потому что для нормального фикса
# нужно уходить с сериалайзеров на jbuilder
# Naming/PredicateName:
#   Enabled: false

# why?
Layout/EmptyLinesAroundClassBody:
  Enabled: false

RSpec/Rails/AvoidSetupHook:
  Enabled: false
