allowBuilds:
  '@sentry/cli': true
  '@swc/core': true
  sharp: true
  simple-git-hooks: true
minimumReleaseAgeExclude:
  - npm-check-updates@22.2.8
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@swc/core'
  - esbuild
  - sharp
  - simple-git-hooks
