# typed: true
# frozen_string_literal: true

require "English"
require "action_cable/channel/base"
require "action_cable/connection/base"
require "action_cable/engine"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_text/engine"
require "action_view/railtie"
require "active_job/railtie"
require "active_model/railtie"
require "active_record/railtie"
require "active_storage/engine"
require "active_support/core_ext/integer/time"
require "boba"
require "bootsnap/setup"
require "bundler/setup"
require "capybara/cuprite"
require "minitest-power_assert"
require "minitest/autorun"
require "minitest/pride"
require "open3"
require "pty"
require "rails"
require "rails/all"
require "rails/test_help"
require "rails/test_unit/railtie"
require "securerandom"
require "sorbet-schema"
require "tapioca/dsl"
require "webauthn/fake_client"
require "webmock/minitest"
