// Typelizer digest 90fea31a5c21f0961fa8c87d567ea520
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {MemberState} from '@/types'

type LanguageMember = {
  id: number;
  user_id: number;
  language_id: number;
  state: MemberState | null;
  progress: number;
  next_lesson_name: string | null;
}

export default LanguageMember;
