FROM hexletbasics/hexlet-basics:cached-base

COPY package.json .
COPY yarn.lock .

RUN yarn install

COPY Gemfile .
COPY Gemfile.lock .

RUN bundle config set without 'development'

RUN bundle install --jobs $(nproc)

COPY . .

RUN NODE_ENV=production RAILS_ENV=production SECRET_KEY_BASE=jopa bin/rails assets:precompile --trace

VOLUME /var/tmp/hexletbasics
