# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'configus'
gem 'puma', '~> 5.1'
gem 'rails', '~> 6.1'
gem 'sass-rails', '>= 6'
gem 'webpacker', '~> 5.2'

gem 'bootsnap', '>= 1.5', require: false
gem 'http_accept_language'
gem 'jbuilder', '~> 2.10'
gem 'kaminari'
gem 'omniauth-github'
gem 'ransack'
gem 'rollbar'
gem 'term-ansicolor'
gem 'valid_email2'
gem 'sorbet-runtime'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'sorbet'
  gem 'dotenv-rails'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'sqlite3', '~> 1.4'
end

group :development do
  gem 'i18n-debug'
  gem 'listen', '>= 3.3.3'
  gem 'rubocop'
  gem 'spring'
  # gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'minitest-power_assert'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end

group :production do
  gem 'pg'
end

gem 'aasm'
gem 'active_form_model'
gem 'bcrypt'
gem 'dry-auto_inject'
gem 'dry-container'
gem 'enumerize'
gem 'gon'
gem 'js-routes'
gem 'rails-i18n'
gem 'redcarpet', '~> 3.5'
gem 'reform-rails'
gem 'sidekiq'
gem 'simple_form'
gem 'slim-rails'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
