// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"hexletbasics/ent/courselessontranslation"
	"hexletbasics/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CourseLessonTranslationDelete is the builder for deleting a CourseLessonTranslation entity.
type CourseLessonTranslationDelete struct {
	config
	hooks    []Hook
	mutation *CourseLessonTranslationMutation
}

// Where appends a list predicates to the CourseLessonTranslationDelete builder.
func (_d *CourseLessonTranslationDelete) Where(ps ...predicate.CourseLessonTranslation) *CourseLessonTranslationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CourseLessonTranslationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CourseLessonTranslationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CourseLessonTranslationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(courselessontranslation.Table, sqlgraph.NewFieldSpec(courselessontranslation.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CourseLessonTranslationDeleteOne is the builder for deleting a single CourseLessonTranslation entity.
type CourseLessonTranslationDeleteOne struct {
	_d *CourseLessonTranslationDelete
}

// Where appends a list predicates to the CourseLessonTranslationDelete builder.
func (_d *CourseLessonTranslationDeleteOne) Where(ps ...predicate.CourseLessonTranslation) *CourseLessonTranslationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CourseLessonTranslationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{courselessontranslation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CourseLessonTranslationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
