// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hexletbasics/ent/courselesson"
	"hexletbasics/ent/courselessontranslation"
	"hexletbasics/ent/courselessonversion"
	"hexletbasics/ent/courseversion"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CourseLessonTranslationCreate is the builder for creating a CourseLessonTranslation entity.
type CourseLessonTranslationCreate struct {
	config
	mutation *CourseLessonTranslationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CourseLessonTranslationCreate) SetCreatedAt(v time.Time) *CourseLessonTranslationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CourseLessonTranslationCreate) SetNillableCreatedAt(v *time.Time) *CourseLessonTranslationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CourseLessonTranslationCreate) SetUpdatedAt(v time.Time) *CourseLessonTranslationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CourseLessonTranslationCreate) SetNillableUpdatedAt(v *time.Time) *CourseLessonTranslationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *CourseLessonTranslationCreate) SetName(v string) *CourseLessonTranslationCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *CourseLessonTranslationCreate) SetNillableName(v *string) *CourseLessonTranslationCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *CourseLessonTranslationCreate) SetDescription(v string) *CourseLessonTranslationCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *CourseLessonTranslationCreate) SetNillableDescription(v *string) *CourseLessonTranslationCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetLocale sets the "locale" field.
func (_c *CourseLessonTranslationCreate) SetLocale(v string) *CourseLessonTranslationCreate {
	_c.mutation.SetLocale(v)
	return _c
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (_c *CourseLessonTranslationCreate) SetNillableLocale(v *string) *CourseLessonTranslationCreate {
	if v != nil {
		_c.SetLocale(*v)
	}
	return _c
}

// SetCourseID sets the "course_id" field.
func (_c *CourseLessonTranslationCreate) SetCourseID(v int) *CourseLessonTranslationCreate {
	_c.mutation.SetCourseID(v)
	return _c
}

// SetCourseLessonID sets the "course_lesson_id" field.
func (_c *CourseLessonTranslationCreate) SetCourseLessonID(v int) *CourseLessonTranslationCreate {
	_c.mutation.SetCourseLessonID(v)
	return _c
}

// SetCourseVersionID sets the "course_version_id" field.
func (_c *CourseLessonTranslationCreate) SetCourseVersionID(v int) *CourseLessonTranslationCreate {
	_c.mutation.SetCourseVersionID(v)
	return _c
}

// SetTheory sets the "theory" field.
func (_c *CourseLessonTranslationCreate) SetTheory(v string) *CourseLessonTranslationCreate {
	_c.mutation.SetTheory(v)
	return _c
}

// SetNillableTheory sets the "theory" field if the given value is not nil.
func (_c *CourseLessonTranslationCreate) SetNillableTheory(v *string) *CourseLessonTranslationCreate {
	if v != nil {
		_c.SetTheory(*v)
	}
	return _c
}

// SetInstructions sets the "instructions" field.
func (_c *CourseLessonTranslationCreate) SetInstructions(v string) *CourseLessonTranslationCreate {
	_c.mutation.SetInstructions(v)
	return _c
}

// SetNillableInstructions sets the "instructions" field if the given value is not nil.
func (_c *CourseLessonTranslationCreate) SetNillableInstructions(v *string) *CourseLessonTranslationCreate {
	if v != nil {
		_c.SetInstructions(*v)
	}
	return _c
}

// SetTips sets the "tips" field.
func (_c *CourseLessonTranslationCreate) SetTips(v string) *CourseLessonTranslationCreate {
	_c.mutation.SetTips(v)
	return _c
}

// SetNillableTips sets the "tips" field if the given value is not nil.
func (_c *CourseLessonTranslationCreate) SetNillableTips(v *string) *CourseLessonTranslationCreate {
	if v != nil {
		_c.SetTips(*v)
	}
	return _c
}

// SetDefinitions sets the "definitions" field.
func (_c *CourseLessonTranslationCreate) SetDefinitions(v string) *CourseLessonTranslationCreate {
	_c.mutation.SetDefinitions(v)
	return _c
}

// SetNillableDefinitions sets the "definitions" field if the given value is not nil.
func (_c *CourseLessonTranslationCreate) SetNillableDefinitions(v *string) *CourseLessonTranslationCreate {
	if v != nil {
		_c.SetDefinitions(*v)
	}
	return _c
}

// SetVersionID sets the "version_id" field.
func (_c *CourseLessonTranslationCreate) SetVersionID(v int) *CourseLessonTranslationCreate {
	_c.mutation.SetVersionID(v)
	return _c
}

// SetLessonID sets the "lesson" edge to the CourseLesson entity by ID.
func (_c *CourseLessonTranslationCreate) SetLessonID(id int) *CourseLessonTranslationCreate {
	_c.mutation.SetLessonID(id)
	return _c
}

// SetLesson sets the "lesson" edge to the CourseLesson entity.
func (_c *CourseLessonTranslationCreate) SetLesson(v *CourseLesson) *CourseLessonTranslationCreate {
	return _c.SetLessonID(v.ID)
}

// SetCourseVersion sets the "course_version" edge to the CourseVersion entity.
func (_c *CourseLessonTranslationCreate) SetCourseVersion(v *CourseVersion) *CourseLessonTranslationCreate {
	return _c.SetCourseVersionID(v.ID)
}

// SetVersion sets the "version" edge to the CourseLessonVersion entity.
func (_c *CourseLessonTranslationCreate) SetVersion(v *CourseLessonVersion) *CourseLessonTranslationCreate {
	return _c.SetVersionID(v.ID)
}

// Mutation returns the CourseLessonTranslationMutation object of the builder.
func (_c *CourseLessonTranslationCreate) Mutation() *CourseLessonTranslationMutation {
	return _c.mutation
}

// Save creates the CourseLessonTranslation in the database.
func (_c *CourseLessonTranslationCreate) Save(ctx context.Context) (*CourseLessonTranslation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CourseLessonTranslationCreate) SaveX(ctx context.Context) *CourseLessonTranslation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseLessonTranslationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseLessonTranslationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CourseLessonTranslationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := courselessontranslation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := courselessontranslation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CourseLessonTranslationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CourseLessonTranslation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CourseLessonTranslation.updated_at"`)}
	}
	if _, ok := _c.mutation.CourseID(); !ok {
		return &ValidationError{Name: "course_id", err: errors.New(`ent: missing required field "CourseLessonTranslation.course_id"`)}
	}
	if _, ok := _c.mutation.CourseLessonID(); !ok {
		return &ValidationError{Name: "course_lesson_id", err: errors.New(`ent: missing required field "CourseLessonTranslation.course_lesson_id"`)}
	}
	if _, ok := _c.mutation.CourseVersionID(); !ok {
		return &ValidationError{Name: "course_version_id", err: errors.New(`ent: missing required field "CourseLessonTranslation.course_version_id"`)}
	}
	if _, ok := _c.mutation.VersionID(); !ok {
		return &ValidationError{Name: "version_id", err: errors.New(`ent: missing required field "CourseLessonTranslation.version_id"`)}
	}
	if len(_c.mutation.LessonIDs()) == 0 {
		return &ValidationError{Name: "lesson", err: errors.New(`ent: missing required edge "CourseLessonTranslation.lesson"`)}
	}
	if len(_c.mutation.CourseVersionIDs()) == 0 {
		return &ValidationError{Name: "course_version", err: errors.New(`ent: missing required edge "CourseLessonTranslation.course_version"`)}
	}
	if len(_c.mutation.VersionIDs()) == 0 {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required edge "CourseLessonTranslation.version"`)}
	}
	return nil
}

func (_c *CourseLessonTranslationCreate) sqlSave(ctx context.Context) (*CourseLessonTranslation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CourseLessonTranslationCreate) createSpec() (*CourseLessonTranslation, *sqlgraph.CreateSpec) {
	var (
		_node = &CourseLessonTranslation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(courselessontranslation.Table, sqlgraph.NewFieldSpec(courselessontranslation.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(courselessontranslation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(courselessontranslation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(courselessontranslation.FieldName, field.TypeString, value)
		_node.Name = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(courselessontranslation.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Locale(); ok {
		_spec.SetField(courselessontranslation.FieldLocale, field.TypeString, value)
		_node.Locale = &value
	}
	if value, ok := _c.mutation.CourseID(); ok {
		_spec.SetField(courselessontranslation.FieldCourseID, field.TypeInt, value)
		_node.CourseID = value
	}
	if value, ok := _c.mutation.Theory(); ok {
		_spec.SetField(courselessontranslation.FieldTheory, field.TypeString, value)
		_node.Theory = &value
	}
	if value, ok := _c.mutation.Instructions(); ok {
		_spec.SetField(courselessontranslation.FieldInstructions, field.TypeString, value)
		_node.Instructions = &value
	}
	if value, ok := _c.mutation.Tips(); ok {
		_spec.SetField(courselessontranslation.FieldTips, field.TypeString, value)
		_node.Tips = &value
	}
	if value, ok := _c.mutation.Definitions(); ok {
		_spec.SetField(courselessontranslation.FieldDefinitions, field.TypeString, value)
		_node.Definitions = &value
	}
	if nodes := _c.mutation.LessonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   courselessontranslation.LessonTable,
			Columns: []string{courselessontranslation.LessonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courselesson.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CourseLessonID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CourseVersionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   courselessontranslation.CourseVersionTable,
			Columns: []string{courselessontranslation.CourseVersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courseversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CourseVersionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VersionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   courselessontranslation.VersionTable,
			Columns: []string{courselessontranslation.VersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courselessonversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.VersionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CourseLessonTranslation.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CourseLessonTranslationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CourseLessonTranslationCreate) OnConflict(opts ...sql.ConflictOption) *CourseLessonTranslationUpsertOne {
	_c.conflict = opts
	return &CourseLessonTranslationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CourseLessonTranslation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CourseLessonTranslationCreate) OnConflictColumns(columns ...string) *CourseLessonTranslationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CourseLessonTranslationUpsertOne{
		create: _c,
	}
}

type (
	// CourseLessonTranslationUpsertOne is the builder for "upsert"-ing
	//  one CourseLessonTranslation node.
	CourseLessonTranslationUpsertOne struct {
		create *CourseLessonTranslationCreate
	}

	// CourseLessonTranslationUpsert is the "OnConflict" setter.
	CourseLessonTranslationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CourseLessonTranslationUpsert) SetUpdatedAt(v time.Time) *CourseLessonTranslationUpsert {
	u.Set(courselessontranslation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsert) UpdateUpdatedAt() *CourseLessonTranslationUpsert {
	u.SetExcluded(courselessontranslation.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *CourseLessonTranslationUpsert) SetName(v string) *CourseLessonTranslationUpsert {
	u.Set(courselessontranslation.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsert) UpdateName() *CourseLessonTranslationUpsert {
	u.SetExcluded(courselessontranslation.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *CourseLessonTranslationUpsert) ClearName() *CourseLessonTranslationUpsert {
	u.SetNull(courselessontranslation.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *CourseLessonTranslationUpsert) SetDescription(v string) *CourseLessonTranslationUpsert {
	u.Set(courselessontranslation.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsert) UpdateDescription() *CourseLessonTranslationUpsert {
	u.SetExcluded(courselessontranslation.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *CourseLessonTranslationUpsert) ClearDescription() *CourseLessonTranslationUpsert {
	u.SetNull(courselessontranslation.FieldDescription)
	return u
}

// SetLocale sets the "locale" field.
func (u *CourseLessonTranslationUpsert) SetLocale(v string) *CourseLessonTranslationUpsert {
	u.Set(courselessontranslation.FieldLocale, v)
	return u
}

// UpdateLocale sets the "locale" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsert) UpdateLocale() *CourseLessonTranslationUpsert {
	u.SetExcluded(courselessontranslation.FieldLocale)
	return u
}

// ClearLocale clears the value of the "locale" field.
func (u *CourseLessonTranslationUpsert) ClearLocale() *CourseLessonTranslationUpsert {
	u.SetNull(courselessontranslation.FieldLocale)
	return u
}

// SetCourseID sets the "course_id" field.
func (u *CourseLessonTranslationUpsert) SetCourseID(v int) *CourseLessonTranslationUpsert {
	u.Set(courselessontranslation.FieldCourseID, v)
	return u
}

// UpdateCourseID sets the "course_id" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsert) UpdateCourseID() *CourseLessonTranslationUpsert {
	u.SetExcluded(courselessontranslation.FieldCourseID)
	return u
}

// AddCourseID adds v to the "course_id" field.
func (u *CourseLessonTranslationUpsert) AddCourseID(v int) *CourseLessonTranslationUpsert {
	u.Add(courselessontranslation.FieldCourseID, v)
	return u
}

// SetCourseLessonID sets the "course_lesson_id" field.
func (u *CourseLessonTranslationUpsert) SetCourseLessonID(v int) *CourseLessonTranslationUpsert {
	u.Set(courselessontranslation.FieldCourseLessonID, v)
	return u
}

// UpdateCourseLessonID sets the "course_lesson_id" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsert) UpdateCourseLessonID() *CourseLessonTranslationUpsert {
	u.SetExcluded(courselessontranslation.FieldCourseLessonID)
	return u
}

// SetCourseVersionID sets the "course_version_id" field.
func (u *CourseLessonTranslationUpsert) SetCourseVersionID(v int) *CourseLessonTranslationUpsert {
	u.Set(courselessontranslation.FieldCourseVersionID, v)
	return u
}

// UpdateCourseVersionID sets the "course_version_id" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsert) UpdateCourseVersionID() *CourseLessonTranslationUpsert {
	u.SetExcluded(courselessontranslation.FieldCourseVersionID)
	return u
}

// SetTheory sets the "theory" field.
func (u *CourseLessonTranslationUpsert) SetTheory(v string) *CourseLessonTranslationUpsert {
	u.Set(courselessontranslation.FieldTheory, v)
	return u
}

// UpdateTheory sets the "theory" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsert) UpdateTheory() *CourseLessonTranslationUpsert {
	u.SetExcluded(courselessontranslation.FieldTheory)
	return u
}

// ClearTheory clears the value of the "theory" field.
func (u *CourseLessonTranslationUpsert) ClearTheory() *CourseLessonTranslationUpsert {
	u.SetNull(courselessontranslation.FieldTheory)
	return u
}

// SetInstructions sets the "instructions" field.
func (u *CourseLessonTranslationUpsert) SetInstructions(v string) *CourseLessonTranslationUpsert {
	u.Set(courselessontranslation.FieldInstructions, v)
	return u
}

// UpdateInstructions sets the "instructions" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsert) UpdateInstructions() *CourseLessonTranslationUpsert {
	u.SetExcluded(courselessontranslation.FieldInstructions)
	return u
}

// ClearInstructions clears the value of the "instructions" field.
func (u *CourseLessonTranslationUpsert) ClearInstructions() *CourseLessonTranslationUpsert {
	u.SetNull(courselessontranslation.FieldInstructions)
	return u
}

// SetTips sets the "tips" field.
func (u *CourseLessonTranslationUpsert) SetTips(v string) *CourseLessonTranslationUpsert {
	u.Set(courselessontranslation.FieldTips, v)
	return u
}

// UpdateTips sets the "tips" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsert) UpdateTips() *CourseLessonTranslationUpsert {
	u.SetExcluded(courselessontranslation.FieldTips)
	return u
}

// ClearTips clears the value of the "tips" field.
func (u *CourseLessonTranslationUpsert) ClearTips() *CourseLessonTranslationUpsert {
	u.SetNull(courselessontranslation.FieldTips)
	return u
}

// SetDefinitions sets the "definitions" field.
func (u *CourseLessonTranslationUpsert) SetDefinitions(v string) *CourseLessonTranslationUpsert {
	u.Set(courselessontranslation.FieldDefinitions, v)
	return u
}

// UpdateDefinitions sets the "definitions" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsert) UpdateDefinitions() *CourseLessonTranslationUpsert {
	u.SetExcluded(courselessontranslation.FieldDefinitions)
	return u
}

// ClearDefinitions clears the value of the "definitions" field.
func (u *CourseLessonTranslationUpsert) ClearDefinitions() *CourseLessonTranslationUpsert {
	u.SetNull(courselessontranslation.FieldDefinitions)
	return u
}

// SetVersionID sets the "version_id" field.
func (u *CourseLessonTranslationUpsert) SetVersionID(v int) *CourseLessonTranslationUpsert {
	u.Set(courselessontranslation.FieldVersionID, v)
	return u
}

// UpdateVersionID sets the "version_id" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsert) UpdateVersionID() *CourseLessonTranslationUpsert {
	u.SetExcluded(courselessontranslation.FieldVersionID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CourseLessonTranslation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CourseLessonTranslationUpsertOne) UpdateNewValues() *CourseLessonTranslationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(courselessontranslation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CourseLessonTranslation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CourseLessonTranslationUpsertOne) Ignore() *CourseLessonTranslationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CourseLessonTranslationUpsertOne) DoNothing() *CourseLessonTranslationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CourseLessonTranslationCreate.OnConflict
// documentation for more info.
func (u *CourseLessonTranslationUpsertOne) Update(set func(*CourseLessonTranslationUpsert)) *CourseLessonTranslationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CourseLessonTranslationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CourseLessonTranslationUpsertOne) SetUpdatedAt(v time.Time) *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertOne) UpdateUpdatedAt() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *CourseLessonTranslationUpsertOne) SetName(v string) *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertOne) UpdateName() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *CourseLessonTranslationUpsertOne) ClearName() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.ClearName()
	})
}

// SetDescription sets the "description" field.
func (u *CourseLessonTranslationUpsertOne) SetDescription(v string) *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertOne) UpdateDescription() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *CourseLessonTranslationUpsertOne) ClearDescription() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.ClearDescription()
	})
}

// SetLocale sets the "locale" field.
func (u *CourseLessonTranslationUpsertOne) SetLocale(v string) *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetLocale(v)
	})
}

// UpdateLocale sets the "locale" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertOne) UpdateLocale() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateLocale()
	})
}

// ClearLocale clears the value of the "locale" field.
func (u *CourseLessonTranslationUpsertOne) ClearLocale() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.ClearLocale()
	})
}

// SetCourseID sets the "course_id" field.
func (u *CourseLessonTranslationUpsertOne) SetCourseID(v int) *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetCourseID(v)
	})
}

// AddCourseID adds v to the "course_id" field.
func (u *CourseLessonTranslationUpsertOne) AddCourseID(v int) *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.AddCourseID(v)
	})
}

// UpdateCourseID sets the "course_id" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertOne) UpdateCourseID() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateCourseID()
	})
}

// SetCourseLessonID sets the "course_lesson_id" field.
func (u *CourseLessonTranslationUpsertOne) SetCourseLessonID(v int) *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetCourseLessonID(v)
	})
}

// UpdateCourseLessonID sets the "course_lesson_id" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertOne) UpdateCourseLessonID() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateCourseLessonID()
	})
}

// SetCourseVersionID sets the "course_version_id" field.
func (u *CourseLessonTranslationUpsertOne) SetCourseVersionID(v int) *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetCourseVersionID(v)
	})
}

// UpdateCourseVersionID sets the "course_version_id" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertOne) UpdateCourseVersionID() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateCourseVersionID()
	})
}

// SetTheory sets the "theory" field.
func (u *CourseLessonTranslationUpsertOne) SetTheory(v string) *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetTheory(v)
	})
}

// UpdateTheory sets the "theory" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertOne) UpdateTheory() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateTheory()
	})
}

// ClearTheory clears the value of the "theory" field.
func (u *CourseLessonTranslationUpsertOne) ClearTheory() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.ClearTheory()
	})
}

// SetInstructions sets the "instructions" field.
func (u *CourseLessonTranslationUpsertOne) SetInstructions(v string) *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetInstructions(v)
	})
}

// UpdateInstructions sets the "instructions" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertOne) UpdateInstructions() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateInstructions()
	})
}

// ClearInstructions clears the value of the "instructions" field.
func (u *CourseLessonTranslationUpsertOne) ClearInstructions() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.ClearInstructions()
	})
}

// SetTips sets the "tips" field.
func (u *CourseLessonTranslationUpsertOne) SetTips(v string) *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetTips(v)
	})
}

// UpdateTips sets the "tips" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertOne) UpdateTips() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateTips()
	})
}

// ClearTips clears the value of the "tips" field.
func (u *CourseLessonTranslationUpsertOne) ClearTips() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.ClearTips()
	})
}

// SetDefinitions sets the "definitions" field.
func (u *CourseLessonTranslationUpsertOne) SetDefinitions(v string) *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetDefinitions(v)
	})
}

// UpdateDefinitions sets the "definitions" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertOne) UpdateDefinitions() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateDefinitions()
	})
}

// ClearDefinitions clears the value of the "definitions" field.
func (u *CourseLessonTranslationUpsertOne) ClearDefinitions() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.ClearDefinitions()
	})
}

// SetVersionID sets the "version_id" field.
func (u *CourseLessonTranslationUpsertOne) SetVersionID(v int) *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetVersionID(v)
	})
}

// UpdateVersionID sets the "version_id" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertOne) UpdateVersionID() *CourseLessonTranslationUpsertOne {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateVersionID()
	})
}

// Exec executes the query.
func (u *CourseLessonTranslationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CourseLessonTranslationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CourseLessonTranslationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CourseLessonTranslationUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CourseLessonTranslationUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CourseLessonTranslationCreateBulk is the builder for creating many CourseLessonTranslation entities in bulk.
type CourseLessonTranslationCreateBulk struct {
	config
	err      error
	builders []*CourseLessonTranslationCreate
	conflict []sql.ConflictOption
}

// Save creates the CourseLessonTranslation entities in the database.
func (_c *CourseLessonTranslationCreateBulk) Save(ctx context.Context) ([]*CourseLessonTranslation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CourseLessonTranslation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CourseLessonTranslationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CourseLessonTranslationCreateBulk) SaveX(ctx context.Context) []*CourseLessonTranslation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseLessonTranslationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseLessonTranslationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CourseLessonTranslation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CourseLessonTranslationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CourseLessonTranslationCreateBulk) OnConflict(opts ...sql.ConflictOption) *CourseLessonTranslationUpsertBulk {
	_c.conflict = opts
	return &CourseLessonTranslationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CourseLessonTranslation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CourseLessonTranslationCreateBulk) OnConflictColumns(columns ...string) *CourseLessonTranslationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CourseLessonTranslationUpsertBulk{
		create: _c,
	}
}

// CourseLessonTranslationUpsertBulk is the builder for "upsert"-ing
// a bulk of CourseLessonTranslation nodes.
type CourseLessonTranslationUpsertBulk struct {
	create *CourseLessonTranslationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CourseLessonTranslation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CourseLessonTranslationUpsertBulk) UpdateNewValues() *CourseLessonTranslationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(courselessontranslation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CourseLessonTranslation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CourseLessonTranslationUpsertBulk) Ignore() *CourseLessonTranslationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CourseLessonTranslationUpsertBulk) DoNothing() *CourseLessonTranslationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CourseLessonTranslationCreateBulk.OnConflict
// documentation for more info.
func (u *CourseLessonTranslationUpsertBulk) Update(set func(*CourseLessonTranslationUpsert)) *CourseLessonTranslationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CourseLessonTranslationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CourseLessonTranslationUpsertBulk) SetUpdatedAt(v time.Time) *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertBulk) UpdateUpdatedAt() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *CourseLessonTranslationUpsertBulk) SetName(v string) *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertBulk) UpdateName() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *CourseLessonTranslationUpsertBulk) ClearName() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.ClearName()
	})
}

// SetDescription sets the "description" field.
func (u *CourseLessonTranslationUpsertBulk) SetDescription(v string) *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertBulk) UpdateDescription() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *CourseLessonTranslationUpsertBulk) ClearDescription() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.ClearDescription()
	})
}

// SetLocale sets the "locale" field.
func (u *CourseLessonTranslationUpsertBulk) SetLocale(v string) *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetLocale(v)
	})
}

// UpdateLocale sets the "locale" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertBulk) UpdateLocale() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateLocale()
	})
}

// ClearLocale clears the value of the "locale" field.
func (u *CourseLessonTranslationUpsertBulk) ClearLocale() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.ClearLocale()
	})
}

// SetCourseID sets the "course_id" field.
func (u *CourseLessonTranslationUpsertBulk) SetCourseID(v int) *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetCourseID(v)
	})
}

// AddCourseID adds v to the "course_id" field.
func (u *CourseLessonTranslationUpsertBulk) AddCourseID(v int) *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.AddCourseID(v)
	})
}

// UpdateCourseID sets the "course_id" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertBulk) UpdateCourseID() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateCourseID()
	})
}

// SetCourseLessonID sets the "course_lesson_id" field.
func (u *CourseLessonTranslationUpsertBulk) SetCourseLessonID(v int) *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetCourseLessonID(v)
	})
}

// UpdateCourseLessonID sets the "course_lesson_id" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertBulk) UpdateCourseLessonID() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateCourseLessonID()
	})
}

// SetCourseVersionID sets the "course_version_id" field.
func (u *CourseLessonTranslationUpsertBulk) SetCourseVersionID(v int) *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetCourseVersionID(v)
	})
}

// UpdateCourseVersionID sets the "course_version_id" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertBulk) UpdateCourseVersionID() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateCourseVersionID()
	})
}

// SetTheory sets the "theory" field.
func (u *CourseLessonTranslationUpsertBulk) SetTheory(v string) *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetTheory(v)
	})
}

// UpdateTheory sets the "theory" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertBulk) UpdateTheory() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateTheory()
	})
}

// ClearTheory clears the value of the "theory" field.
func (u *CourseLessonTranslationUpsertBulk) ClearTheory() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.ClearTheory()
	})
}

// SetInstructions sets the "instructions" field.
func (u *CourseLessonTranslationUpsertBulk) SetInstructions(v string) *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetInstructions(v)
	})
}

// UpdateInstructions sets the "instructions" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertBulk) UpdateInstructions() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateInstructions()
	})
}

// ClearInstructions clears the value of the "instructions" field.
func (u *CourseLessonTranslationUpsertBulk) ClearInstructions() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.ClearInstructions()
	})
}

// SetTips sets the "tips" field.
func (u *CourseLessonTranslationUpsertBulk) SetTips(v string) *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetTips(v)
	})
}

// UpdateTips sets the "tips" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertBulk) UpdateTips() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateTips()
	})
}

// ClearTips clears the value of the "tips" field.
func (u *CourseLessonTranslationUpsertBulk) ClearTips() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.ClearTips()
	})
}

// SetDefinitions sets the "definitions" field.
func (u *CourseLessonTranslationUpsertBulk) SetDefinitions(v string) *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetDefinitions(v)
	})
}

// UpdateDefinitions sets the "definitions" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertBulk) UpdateDefinitions() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateDefinitions()
	})
}

// ClearDefinitions clears the value of the "definitions" field.
func (u *CourseLessonTranslationUpsertBulk) ClearDefinitions() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.ClearDefinitions()
	})
}

// SetVersionID sets the "version_id" field.
func (u *CourseLessonTranslationUpsertBulk) SetVersionID(v int) *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.SetVersionID(v)
	})
}

// UpdateVersionID sets the "version_id" field to the value that was provided on create.
func (u *CourseLessonTranslationUpsertBulk) UpdateVersionID() *CourseLessonTranslationUpsertBulk {
	return u.Update(func(s *CourseLessonTranslationUpsert) {
		s.UpdateVersionID()
	})
}

// Exec executes the query.
func (u *CourseLessonTranslationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CourseLessonTranslationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CourseLessonTranslationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CourseLessonTranslationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
