// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hexletbasics/ent/coursemodule"
	"hexletbasics/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CourseModuleUpdate is the builder for updating CourseModule entities.
type CourseModuleUpdate struct {
	config
	hooks    []Hook
	mutation *CourseModuleMutation
}

// Where appends a list predicates to the CourseModuleUpdate builder.
func (_u *CourseModuleUpdate) Where(ps ...predicate.CourseModule) *CourseModuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CourseModuleUpdate) SetUpdatedAt(v time.Time) *CourseModuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *CourseModuleUpdate) SetSlug(v string) *CourseModuleUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *CourseModuleUpdate) SetNillableSlug(v *string) *CourseModuleUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// ClearSlug clears the value of the "slug" field.
func (_u *CourseModuleUpdate) ClearSlug() *CourseModuleUpdate {
	_u.mutation.ClearSlug()
	return _u
}

// SetCourseID sets the "course_id" field.
func (_u *CourseModuleUpdate) SetCourseID(v int) *CourseModuleUpdate {
	_u.mutation.ResetCourseID()
	_u.mutation.SetCourseID(v)
	return _u
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (_u *CourseModuleUpdate) SetNillableCourseID(v *int) *CourseModuleUpdate {
	if v != nil {
		_u.SetCourseID(*v)
	}
	return _u
}

// AddCourseID adds value to the "course_id" field.
func (_u *CourseModuleUpdate) AddCourseID(v int) *CourseModuleUpdate {
	_u.mutation.AddCourseID(v)
	return _u
}

// ClearCourseID clears the value of the "course_id" field.
func (_u *CourseModuleUpdate) ClearCourseID() *CourseModuleUpdate {
	_u.mutation.ClearCourseID()
	return _u
}

// SetOrder sets the "order" field.
func (_u *CourseModuleUpdate) SetOrder(v int) *CourseModuleUpdate {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *CourseModuleUpdate) SetNillableOrder(v *int) *CourseModuleUpdate {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *CourseModuleUpdate) AddOrder(v int) *CourseModuleUpdate {
	_u.mutation.AddOrder(v)
	return _u
}

// ClearOrder clears the value of the "order" field.
func (_u *CourseModuleUpdate) ClearOrder() *CourseModuleUpdate {
	_u.mutation.ClearOrder()
	return _u
}

// SetState sets the "state" field.
func (_u *CourseModuleUpdate) SetState(v string) *CourseModuleUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *CourseModuleUpdate) SetNillableState(v *string) *CourseModuleUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// ClearState clears the value of the "state" field.
func (_u *CourseModuleUpdate) ClearState() *CourseModuleUpdate {
	_u.mutation.ClearState()
	return _u
}

// Mutation returns the CourseModuleMutation object of the builder.
func (_u *CourseModuleUpdate) Mutation() *CourseModuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CourseModuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CourseModuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CourseModuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CourseModuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CourseModuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := coursemodule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *CourseModuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(coursemodule.Table, coursemodule.Columns, sqlgraph.NewFieldSpec(coursemodule.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(coursemodule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(coursemodule.FieldSlug, field.TypeString, value)
	}
	if _u.mutation.SlugCleared() {
		_spec.ClearField(coursemodule.FieldSlug, field.TypeString)
	}
	if value, ok := _u.mutation.CourseID(); ok {
		_spec.SetField(coursemodule.FieldCourseID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCourseID(); ok {
		_spec.AddField(coursemodule.FieldCourseID, field.TypeInt, value)
	}
	if _u.mutation.CourseIDCleared() {
		_spec.ClearField(coursemodule.FieldCourseID, field.TypeInt)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(coursemodule.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(coursemodule.FieldOrder, field.TypeInt, value)
	}
	if _u.mutation.OrderCleared() {
		_spec.ClearField(coursemodule.FieldOrder, field.TypeInt)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(coursemodule.FieldState, field.TypeString, value)
	}
	if _u.mutation.StateCleared() {
		_spec.ClearField(coursemodule.FieldState, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coursemodule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CourseModuleUpdateOne is the builder for updating a single CourseModule entity.
type CourseModuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CourseModuleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CourseModuleUpdateOne) SetUpdatedAt(v time.Time) *CourseModuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *CourseModuleUpdateOne) SetSlug(v string) *CourseModuleUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *CourseModuleUpdateOne) SetNillableSlug(v *string) *CourseModuleUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// ClearSlug clears the value of the "slug" field.
func (_u *CourseModuleUpdateOne) ClearSlug() *CourseModuleUpdateOne {
	_u.mutation.ClearSlug()
	return _u
}

// SetCourseID sets the "course_id" field.
func (_u *CourseModuleUpdateOne) SetCourseID(v int) *CourseModuleUpdateOne {
	_u.mutation.ResetCourseID()
	_u.mutation.SetCourseID(v)
	return _u
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (_u *CourseModuleUpdateOne) SetNillableCourseID(v *int) *CourseModuleUpdateOne {
	if v != nil {
		_u.SetCourseID(*v)
	}
	return _u
}

// AddCourseID adds value to the "course_id" field.
func (_u *CourseModuleUpdateOne) AddCourseID(v int) *CourseModuleUpdateOne {
	_u.mutation.AddCourseID(v)
	return _u
}

// ClearCourseID clears the value of the "course_id" field.
func (_u *CourseModuleUpdateOne) ClearCourseID() *CourseModuleUpdateOne {
	_u.mutation.ClearCourseID()
	return _u
}

// SetOrder sets the "order" field.
func (_u *CourseModuleUpdateOne) SetOrder(v int) *CourseModuleUpdateOne {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *CourseModuleUpdateOne) SetNillableOrder(v *int) *CourseModuleUpdateOne {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *CourseModuleUpdateOne) AddOrder(v int) *CourseModuleUpdateOne {
	_u.mutation.AddOrder(v)
	return _u
}

// ClearOrder clears the value of the "order" field.
func (_u *CourseModuleUpdateOne) ClearOrder() *CourseModuleUpdateOne {
	_u.mutation.ClearOrder()
	return _u
}

// SetState sets the "state" field.
func (_u *CourseModuleUpdateOne) SetState(v string) *CourseModuleUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *CourseModuleUpdateOne) SetNillableState(v *string) *CourseModuleUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// ClearState clears the value of the "state" field.
func (_u *CourseModuleUpdateOne) ClearState() *CourseModuleUpdateOne {
	_u.mutation.ClearState()
	return _u
}

// Mutation returns the CourseModuleMutation object of the builder.
func (_u *CourseModuleUpdateOne) Mutation() *CourseModuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the CourseModuleUpdate builder.
func (_u *CourseModuleUpdateOne) Where(ps ...predicate.CourseModule) *CourseModuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CourseModuleUpdateOne) Select(field string, fields ...string) *CourseModuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CourseModule entity.
func (_u *CourseModuleUpdateOne) Save(ctx context.Context) (*CourseModule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CourseModuleUpdateOne) SaveX(ctx context.Context) *CourseModule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CourseModuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CourseModuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CourseModuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := coursemodule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *CourseModuleUpdateOne) sqlSave(ctx context.Context) (_node *CourseModule, err error) {
	_spec := sqlgraph.NewUpdateSpec(coursemodule.Table, coursemodule.Columns, sqlgraph.NewFieldSpec(coursemodule.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CourseModule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, coursemodule.FieldID)
		for _, f := range fields {
			if !coursemodule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != coursemodule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(coursemodule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(coursemodule.FieldSlug, field.TypeString, value)
	}
	if _u.mutation.SlugCleared() {
		_spec.ClearField(coursemodule.FieldSlug, field.TypeString)
	}
	if value, ok := _u.mutation.CourseID(); ok {
		_spec.SetField(coursemodule.FieldCourseID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCourseID(); ok {
		_spec.AddField(coursemodule.FieldCourseID, field.TypeInt, value)
	}
	if _u.mutation.CourseIDCleared() {
		_spec.ClearField(coursemodule.FieldCourseID, field.TypeInt)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(coursemodule.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(coursemodule.FieldOrder, field.TypeInt, value)
	}
	if _u.mutation.OrderCleared() {
		_spec.ClearField(coursemodule.FieldOrder, field.TypeInt)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(coursemodule.FieldState, field.TypeString, value)
	}
	if _u.mutation.StateCleared() {
		_spec.ClearField(coursemodule.FieldState, field.TypeString)
	}
	_node = &CourseModule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coursemodule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
