// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hexletbasics/ent/course"
	"hexletbasics/ent/landingpage"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CourseCreate is the builder for creating a Course entity.
type CourseCreate struct {
	config
	mutation *CourseMutation
	hooks    []Hook
}

// SetSlug sets the "slug" field.
func (_c *CourseCreate) SetSlug(v string) *CourseCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_c *CourseCreate) SetNillableSlug(v *string) *CourseCreate {
	if v != nil {
		_c.SetSlug(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *CourseCreate) SetName(v string) *CourseCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *CourseCreate) SetNillableName(v *string) *CourseCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetLearnAs sets the "learn_as" field.
func (_c *CourseCreate) SetLearnAs(v string) *CourseCreate {
	_c.mutation.SetLearnAs(v)
	return _c
}

// SetNillableLearnAs sets the "learn_as" field if the given value is not nil.
func (_c *CourseCreate) SetNillableLearnAs(v *string) *CourseCreate {
	if v != nil {
		_c.SetLearnAs(*v)
	}
	return _c
}

// SetProgress sets the "progress" field.
func (_c *CourseCreate) SetProgress(v string) *CourseCreate {
	_c.mutation.SetProgress(v)
	return _c
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_c *CourseCreate) SetNillableProgress(v *string) *CourseCreate {
	if v != nil {
		_c.SetProgress(*v)
	}
	return _c
}

// SetMembersCount sets the "members_count" field.
func (_c *CourseCreate) SetMembersCount(v int) *CourseCreate {
	_c.mutation.SetMembersCount(v)
	return _c
}

// SetLessonsCount sets the "lessons_count" field.
func (_c *CourseCreate) SetLessonsCount(v int) *CourseCreate {
	_c.mutation.SetLessonsCount(v)
	return _c
}

// SetCategoryID sets the "category_id" field.
func (_c *CourseCreate) SetCategoryID(v int) *CourseCreate {
	_c.mutation.SetCategoryID(v)
	return _c
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_c *CourseCreate) SetNillableCategoryID(v *int) *CourseCreate {
	if v != nil {
		_c.SetCategoryID(*v)
	}
	return _c
}

// SetOrder sets the "order" field.
func (_c *CourseCreate) SetOrder(v int) *CourseCreate {
	_c.mutation.SetOrder(v)
	return _c
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_c *CourseCreate) SetNillableOrder(v *int) *CourseCreate {
	if v != nil {
		_c.SetOrder(*v)
	}
	return _c
}

// AddLandingPageIDs adds the "landing_pages" edge to the LandingPage entity by IDs.
func (_c *CourseCreate) AddLandingPageIDs(ids ...int) *CourseCreate {
	_c.mutation.AddLandingPageIDs(ids...)
	return _c
}

// AddLandingPages adds the "landing_pages" edges to the LandingPage entity.
func (_c *CourseCreate) AddLandingPages(v ...*LandingPage) *CourseCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLandingPageIDs(ids...)
}

// Mutation returns the CourseMutation object of the builder.
func (_c *CourseCreate) Mutation() *CourseMutation {
	return _c.mutation
}

// Save creates the Course in the database.
func (_c *CourseCreate) Save(ctx context.Context) (*Course, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CourseCreate) SaveX(ctx context.Context) *Course {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CourseCreate) check() error {
	if _, ok := _c.mutation.MembersCount(); !ok {
		return &ValidationError{Name: "members_count", err: errors.New(`ent: missing required field "Course.members_count"`)}
	}
	if _, ok := _c.mutation.LessonsCount(); !ok {
		return &ValidationError{Name: "lessons_count", err: errors.New(`ent: missing required field "Course.lessons_count"`)}
	}
	return nil
}

func (_c *CourseCreate) sqlSave(ctx context.Context) (*Course, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CourseCreate) createSpec() (*Course, *sqlgraph.CreateSpec) {
	var (
		_node = &Course{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(course.Table, sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(course.FieldSlug, field.TypeString, value)
		_node.Slug = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(course.FieldName, field.TypeString, value)
		_node.Name = &value
	}
	if value, ok := _c.mutation.LearnAs(); ok {
		_spec.SetField(course.FieldLearnAs, field.TypeString, value)
		_node.LearnAs = &value
	}
	if value, ok := _c.mutation.Progress(); ok {
		_spec.SetField(course.FieldProgress, field.TypeString, value)
		_node.Progress = &value
	}
	if value, ok := _c.mutation.MembersCount(); ok {
		_spec.SetField(course.FieldMembersCount, field.TypeInt, value)
		_node.MembersCount = value
	}
	if value, ok := _c.mutation.LessonsCount(); ok {
		_spec.SetField(course.FieldLessonsCount, field.TypeInt, value)
		_node.LessonsCount = value
	}
	if value, ok := _c.mutation.CategoryID(); ok {
		_spec.SetField(course.FieldCategoryID, field.TypeInt, value)
		_node.CategoryID = &value
	}
	if value, ok := _c.mutation.Order(); ok {
		_spec.SetField(course.FieldOrder, field.TypeInt, value)
		_node.Order = &value
	}
	if nodes := _c.mutation.LandingPagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   course.LandingPagesTable,
			Columns: []string{course.LandingPagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(landingpage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CourseCreateBulk is the builder for creating many Course entities in bulk.
type CourseCreateBulk struct {
	config
	err      error
	builders []*CourseCreate
}

// Save creates the Course entities in the database.
func (_c *CourseCreateBulk) Save(ctx context.Context) ([]*Course, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Course, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CourseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CourseCreateBulk) SaveX(ctx context.Context) []*Course {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
