// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hexletbasics/ent/course"
	"hexletbasics/ent/languagelesson"
	"hexletbasics/ent/languagelessonreview"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LanguageLessonReviewCreate is the builder for creating a LanguageLessonReview entity.
type LanguageLessonReviewCreate struct {
	config
	mutation *LanguageLessonReviewMutation
	hooks    []Hook
}

// SetLocale sets the "locale" field.
func (_c *LanguageLessonReviewCreate) SetLocale(v string) *LanguageLessonReviewCreate {
	_c.mutation.SetLocale(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *LanguageLessonReviewCreate) SetSummary(v string) *LanguageLessonReviewCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetLanguageID sets the "language_id" field.
func (_c *LanguageLessonReviewCreate) SetLanguageID(v int) *LanguageLessonReviewCreate {
	_c.mutation.SetLanguageID(v)
	return _c
}

// SetLanguageLessonID sets the "language_lesson_id" field.
func (_c *LanguageLessonReviewCreate) SetLanguageLessonID(v int) *LanguageLessonReviewCreate {
	_c.mutation.SetLanguageLessonID(v)
	return _c
}

// SetLanguageLessonVersionID sets the "language_lesson_version_id" field.
func (_c *LanguageLessonReviewCreate) SetLanguageLessonVersionID(v int) *LanguageLessonReviewCreate {
	_c.mutation.SetLanguageLessonVersionID(v)
	return _c
}

// SetLanguageLessonVersionInfoID sets the "language_lesson_version_info_id" field.
func (_c *LanguageLessonReviewCreate) SetLanguageLessonVersionInfoID(v int) *LanguageLessonReviewCreate {
	_c.mutation.SetLanguageLessonVersionInfoID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LanguageLessonReviewCreate) SetCreatedAt(v time.Time) *LanguageLessonReviewCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetCourseID sets the "course" edge to the Course entity by ID.
func (_c *LanguageLessonReviewCreate) SetCourseID(id int) *LanguageLessonReviewCreate {
	_c.mutation.SetCourseID(id)
	return _c
}

// SetCourse sets the "course" edge to the Course entity.
func (_c *LanguageLessonReviewCreate) SetCourse(v *Course) *LanguageLessonReviewCreate {
	return _c.SetCourseID(v.ID)
}

// SetLessonID sets the "lesson" edge to the LanguageLesson entity by ID.
func (_c *LanguageLessonReviewCreate) SetLessonID(id int) *LanguageLessonReviewCreate {
	_c.mutation.SetLessonID(id)
	return _c
}

// SetLesson sets the "lesson" edge to the LanguageLesson entity.
func (_c *LanguageLessonReviewCreate) SetLesson(v *LanguageLesson) *LanguageLessonReviewCreate {
	return _c.SetLessonID(v.ID)
}

// Mutation returns the LanguageLessonReviewMutation object of the builder.
func (_c *LanguageLessonReviewCreate) Mutation() *LanguageLessonReviewMutation {
	return _c.mutation
}

// Save creates the LanguageLessonReview in the database.
func (_c *LanguageLessonReviewCreate) Save(ctx context.Context) (*LanguageLessonReview, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LanguageLessonReviewCreate) SaveX(ctx context.Context) *LanguageLessonReview {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LanguageLessonReviewCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LanguageLessonReviewCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LanguageLessonReviewCreate) check() error {
	if _, ok := _c.mutation.Locale(); !ok {
		return &ValidationError{Name: "locale", err: errors.New(`ent: missing required field "LanguageLessonReview.locale"`)}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "LanguageLessonReview.summary"`)}
	}
	if _, ok := _c.mutation.LanguageID(); !ok {
		return &ValidationError{Name: "language_id", err: errors.New(`ent: missing required field "LanguageLessonReview.language_id"`)}
	}
	if _, ok := _c.mutation.LanguageLessonID(); !ok {
		return &ValidationError{Name: "language_lesson_id", err: errors.New(`ent: missing required field "LanguageLessonReview.language_lesson_id"`)}
	}
	if _, ok := _c.mutation.LanguageLessonVersionID(); !ok {
		return &ValidationError{Name: "language_lesson_version_id", err: errors.New(`ent: missing required field "LanguageLessonReview.language_lesson_version_id"`)}
	}
	if _, ok := _c.mutation.LanguageLessonVersionInfoID(); !ok {
		return &ValidationError{Name: "language_lesson_version_info_id", err: errors.New(`ent: missing required field "LanguageLessonReview.language_lesson_version_info_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LanguageLessonReview.created_at"`)}
	}
	if len(_c.mutation.CourseIDs()) == 0 {
		return &ValidationError{Name: "course", err: errors.New(`ent: missing required edge "LanguageLessonReview.course"`)}
	}
	if len(_c.mutation.LessonIDs()) == 0 {
		return &ValidationError{Name: "lesson", err: errors.New(`ent: missing required edge "LanguageLessonReview.lesson"`)}
	}
	return nil
}

func (_c *LanguageLessonReviewCreate) sqlSave(ctx context.Context) (*LanguageLessonReview, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LanguageLessonReviewCreate) createSpec() (*LanguageLessonReview, *sqlgraph.CreateSpec) {
	var (
		_node = &LanguageLessonReview{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(languagelessonreview.Table, sqlgraph.NewFieldSpec(languagelessonreview.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Locale(); ok {
		_spec.SetField(languagelessonreview.FieldLocale, field.TypeString, value)
		_node.Locale = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(languagelessonreview.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.LanguageLessonVersionID(); ok {
		_spec.SetField(languagelessonreview.FieldLanguageLessonVersionID, field.TypeInt, value)
		_node.LanguageLessonVersionID = value
	}
	if value, ok := _c.mutation.LanguageLessonVersionInfoID(); ok {
		_spec.SetField(languagelessonreview.FieldLanguageLessonVersionInfoID, field.TypeInt, value)
		_node.LanguageLessonVersionInfoID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(languagelessonreview.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.CourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   languagelessonreview.CourseTable,
			Columns: []string{languagelessonreview.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LanguageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LessonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   languagelessonreview.LessonTable,
			Columns: []string{languagelessonreview.LessonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(languagelesson.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LanguageLessonID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LanguageLessonReviewCreateBulk is the builder for creating many LanguageLessonReview entities in bulk.
type LanguageLessonReviewCreateBulk struct {
	config
	err      error
	builders []*LanguageLessonReviewCreate
}

// Save creates the LanguageLessonReview entities in the database.
func (_c *LanguageLessonReviewCreateBulk) Save(ctx context.Context) ([]*LanguageLessonReview, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LanguageLessonReview, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LanguageLessonReviewMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LanguageLessonReviewCreateBulk) SaveX(ctx context.Context) []*LanguageLessonReview {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LanguageLessonReviewCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LanguageLessonReviewCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
