apiVersion: v1
kind: Secret
metadata:
  name: "docker-config"
  labels:
    {{- include "codebasics.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerConfig | b64enc | quote }}
