// Code generated by ent, DO NOT EDIT.

package activestorageblob

import (
	"hexletbasics/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldLTE(FieldID, id))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldEQ(FieldKey, v))
}

// Filename applies equality check predicate on the "filename" field. It's identical to FilenameEQ.
func Filename(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldEQ(FieldFilename, v))
}

// ContentType applies equality check predicate on the "content_type" field. It's identical to ContentTypeEQ.
func ContentType(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldEQ(FieldContentType, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldContainsFold(FieldKey, v))
}

// FilenameEQ applies the EQ predicate on the "filename" field.
func FilenameEQ(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldEQ(FieldFilename, v))
}

// FilenameNEQ applies the NEQ predicate on the "filename" field.
func FilenameNEQ(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldNEQ(FieldFilename, v))
}

// FilenameIn applies the In predicate on the "filename" field.
func FilenameIn(vs ...string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldIn(FieldFilename, vs...))
}

// FilenameNotIn applies the NotIn predicate on the "filename" field.
func FilenameNotIn(vs ...string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldNotIn(FieldFilename, vs...))
}

// FilenameGT applies the GT predicate on the "filename" field.
func FilenameGT(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldGT(FieldFilename, v))
}

// FilenameGTE applies the GTE predicate on the "filename" field.
func FilenameGTE(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldGTE(FieldFilename, v))
}

// FilenameLT applies the LT predicate on the "filename" field.
func FilenameLT(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldLT(FieldFilename, v))
}

// FilenameLTE applies the LTE predicate on the "filename" field.
func FilenameLTE(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldLTE(FieldFilename, v))
}

// FilenameContains applies the Contains predicate on the "filename" field.
func FilenameContains(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldContains(FieldFilename, v))
}

// FilenameHasPrefix applies the HasPrefix predicate on the "filename" field.
func FilenameHasPrefix(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldHasPrefix(FieldFilename, v))
}

// FilenameHasSuffix applies the HasSuffix predicate on the "filename" field.
func FilenameHasSuffix(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldHasSuffix(FieldFilename, v))
}

// FilenameEqualFold applies the EqualFold predicate on the "filename" field.
func FilenameEqualFold(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldEqualFold(FieldFilename, v))
}

// FilenameContainsFold applies the ContainsFold predicate on the "filename" field.
func FilenameContainsFold(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldContainsFold(FieldFilename, v))
}

// ContentTypeEQ applies the EQ predicate on the "content_type" field.
func ContentTypeEQ(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldEQ(FieldContentType, v))
}

// ContentTypeNEQ applies the NEQ predicate on the "content_type" field.
func ContentTypeNEQ(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldNEQ(FieldContentType, v))
}

// ContentTypeIn applies the In predicate on the "content_type" field.
func ContentTypeIn(vs ...string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldIn(FieldContentType, vs...))
}

// ContentTypeNotIn applies the NotIn predicate on the "content_type" field.
func ContentTypeNotIn(vs ...string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldNotIn(FieldContentType, vs...))
}

// ContentTypeGT applies the GT predicate on the "content_type" field.
func ContentTypeGT(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldGT(FieldContentType, v))
}

// ContentTypeGTE applies the GTE predicate on the "content_type" field.
func ContentTypeGTE(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldGTE(FieldContentType, v))
}

// ContentTypeLT applies the LT predicate on the "content_type" field.
func ContentTypeLT(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldLT(FieldContentType, v))
}

// ContentTypeLTE applies the LTE predicate on the "content_type" field.
func ContentTypeLTE(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldLTE(FieldContentType, v))
}

// ContentTypeContains applies the Contains predicate on the "content_type" field.
func ContentTypeContains(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldContains(FieldContentType, v))
}

// ContentTypeHasPrefix applies the HasPrefix predicate on the "content_type" field.
func ContentTypeHasPrefix(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldHasPrefix(FieldContentType, v))
}

// ContentTypeHasSuffix applies the HasSuffix predicate on the "content_type" field.
func ContentTypeHasSuffix(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldHasSuffix(FieldContentType, v))
}

// ContentTypeIsNil applies the IsNil predicate on the "content_type" field.
func ContentTypeIsNil() predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldIsNull(FieldContentType))
}

// ContentTypeNotNil applies the NotNil predicate on the "content_type" field.
func ContentTypeNotNil() predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldNotNull(FieldContentType))
}

// ContentTypeEqualFold applies the EqualFold predicate on the "content_type" field.
func ContentTypeEqualFold(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldEqualFold(FieldContentType, v))
}

// ContentTypeContainsFold applies the ContainsFold predicate on the "content_type" field.
func ContentTypeContainsFold(v string) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.FieldContainsFold(FieldContentType, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ActiveStorageBlob) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ActiveStorageBlob) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ActiveStorageBlob) predicate.ActiveStorageBlob {
	return predicate.ActiveStorageBlob(sql.NotPredicates(p))
}
