# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `solid_queue_monitor` gem.
# Please instead update this file by running `bin/tapioca gem solid_queue_monitor`.


# pkg:gem/solid_queue_monitor#lib/solid_queue_monitor/version.rb:3
module SolidQueueMonitor
  class << self
    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:13
    def authentication_enabled; end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:13
    def authentication_enabled=(_arg0); end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:13
    def auto_refresh_enabled; end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:13
    def auto_refresh_enabled=(_arg0); end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:13
    def auto_refresh_interval; end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:13
    def auto_refresh_interval=(_arg0); end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:25
    def base_controller_class; end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:12
    def base_controller_class=(_arg0); end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:13
    def csrf_protection_enabled; end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:13
    def csrf_protection_enabled=(_arg0); end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:13
    def jobs_per_page; end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:13
    def jobs_per_page=(_arg0); end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:21
    def password; end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:12
    def password=(_arg0); end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor/engine.rb:5
    def railtie_helpers_paths; end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor/engine.rb:5
    def railtie_namespace; end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor/engine.rb:5
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:47
    def setup; end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:13
    def show_chart; end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:13
    def show_chart=(_arg0); end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor/engine.rb:5
    def table_name_prefix; end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor/engine.rb:5
    def use_relative_model_naming?; end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:17
    def username; end

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:12
    def username=(_arg0); end

    private

    # pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:31
    def resolve_value(value); end
  end
end

module SolidQueueMonitor::ApplicationHelper
  def asset_url_for(file_name); end
  def csrf_meta_tags_if_enabled; end
  def csrf_token_field_if_enabled; end
  def format_datetime(datetime); end
  def message_class(type); end
  def queue_link(queue_name, css_class: T.unsafe(nil)); end

  private

  def queue_details_url_for(queue_name); end
end

class SolidQueueMonitor::AssetCache
  class << self
    def clear!; end
    def fetch_by_name(file_name); end
    def fingerprint_for(file_name); end

    private

    def path_for(file_name); end
  end
end

SolidQueueMonitor::AssetCache::ASSET_ROOT = T.let(T.unsafe(nil), Pathname)
SolidQueueMonitor::AssetCache::MUTEX = T.let(T.unsafe(nil), Thread::Mutex)
SolidQueueMonitor::AssetCache::SUBDIRS_BY_EXT = T.let(T.unsafe(nil), Hash)

class SolidQueueMonitor::AuthenticationService
  class << self
    def authenticate(username, password); end
    def authentication_required?; end
  end
end

class SolidQueueMonitor::ChartDataService
  def initialize(time_range: T.unsafe(nil)); end

  def calculate; end

  private

  def adapter?(model, name); end
  def bucket_counts(model, column, start_time, end_time, interval, exclude_nil: T.unsafe(nil)); end
  def bucket_index_expr(model, column, start_epoch, interval_seconds); end
  def build_buckets(start_time, bucket_seconds); end
  def fill_buckets(buckets, index_counts); end
end

SolidQueueMonitor::ChartDataService::DEFAULT_TIME_RANGE = T.let(T.unsafe(nil), String)
SolidQueueMonitor::ChartDataService::TIME_RANGES = T.let(T.unsafe(nil), Hash)

module SolidQueueMonitor::ChartHelper
  def chart_time_range_options; end
  def render_chart(data:, time_range: T.unsafe(nil)); end

  private

  def all_series_empty?(context); end
  def calculate_max_value(context); end
  def calculate_points(context, series, max_value); end
  def chart_axes; end
  def chart_body(context); end
  def chart_context(data, time_range); end
  def chart_empty_state; end
  def chart_grid_lines(context); end
  def chart_header(context); end
  def chart_legend; end
  def chart_section(context); end
  def chart_summary(context); end
  def chart_time_select(context); end
  def chart_toggle_button; end
  def chart_tooltip; end
  def chart_x_labels(context); end
  def chart_y_labels(context, max_value); end
  def series_empty?(context, series); end
  def series_line(context, series, max_value); end
  def series_points(context, series, max_value); end
  def x_for_index(context, index, count); end
end

SolidQueueMonitor::ChartHelper::CHART_HEIGHT = T.let(T.unsafe(nil), Integer)
SolidQueueMonitor::ChartHelper::CHART_WIDTH = T.let(T.unsafe(nil), Integer)
SolidQueueMonitor::ChartHelper::COLORS = T.let(T.unsafe(nil), Hash)
SolidQueueMonitor::ChartHelper::PADDING = T.let(T.unsafe(nil), Hash)
SolidQueueMonitor::ChartHelper::SERIES = T.let(T.unsafe(nil), Array)

# pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:9
SolidQueueMonitor::DEFAULT_BASE_CONTROLLER_CLASS = T.let(T.unsafe(nil), String)

# pkg:gem/solid_queue_monitor#lib/solid_queue_monitor/engine.rb:4
class SolidQueueMonitor::Engine < ::Rails::Engine; end

# pkg:gem/solid_queue_monitor#lib/solid_queue_monitor.rb:7
class SolidQueueMonitor::Error < ::StandardError; end

class SolidQueueMonitor::ExecuteJobService
  def call(id); end
  def execute_many(ids); end

  private

  def move_to_ready_queue(execution); end
end

class SolidQueueMonitor::FailedJobService
  def discard_all(job_ids); end
  def discard_job(failed_execution_id); end
  def retry_all(job_ids); end
  def retry_job(failed_execution_id); end

  private

  def get_queue_name(failed_execution, job); end
end

module SolidQueueMonitor::JobDetailsHelper
  def detail_duration(seconds); end
  def detail_job_status(job:, failed_execution:, claimed_execution:, scheduled_execution:); end
  def detail_status_class(status = T.unsafe(nil)); end
  def detail_status_label(status = T.unsafe(nil)); end
  def detail_timing(job:, claimed_execution:, failed_execution:); end
  def pretty_arguments(args); end
  def recent_job_duration(job); end
end

module SolidQueueMonitor::JobsHelper
  def failed_error_message(error); end
  def format_arguments(arguments); end
  def format_hash(hash); end
  def job_status(job); end
  def job_status_badge(job); end
  def mini_job_status_badge(job); end
  def parsed_failed_error(error); end

  private

  def deserialize_failed_error(error); end
  def failed_error_backtrace(error_hash); end
  def failed_error_text(error_hash); end
  def failed_error_type(error_hash); end
  def format_job_arguments(job_data); end
  def mini_job_status(job); end
  def ruby2_keywords_payload?(job_data); end
  def unwrap_arguments(arguments); end
  def wrapped_job_arguments?(arguments); end
end

module SolidQueueMonitor::PaginationHelper
  def pagination_href(page, extra_params = T.unsafe(nil)); end
  def visible_pages(current_page, total_pages); end
end

class SolidQueueMonitor::PaginationService
  def initialize(relation, page, per_page); end

  def paginate; end

  private

  def offset; end
  def paginated_records; end
  def total_pages; end
end

class SolidQueueMonitor::QueuePauseService
  def initialize(queue_name); end

  def pause; end
  def paused?(*_arg0, **_arg1, &_arg2); end
  def resume; end

  class << self
    def paused_queues; end
  end
end

class SolidQueueMonitor::RejectJobService
  def call(id); end
  def reject_many(ids); end

  private

  def reject_job(execution); end
end

class SolidQueueMonitor::SearchService
  def initialize(query); end

  def search; end

  private

  def completed_job_search_conditions; end
  def empty_results; end
  def failed_job_search_conditions; end
  def job_search_conditions; end
  def recurring_task_search_conditions; end
  def sanitize_query(query); end
  def search_completed_jobs(term); end
  def search_failed_jobs(term); end
  def search_in_progress_jobs(term); end
  def search_ready_jobs(term); end
  def search_recurring_tasks(term); end
  def search_scheduled_jobs(term); end
end

SolidQueueMonitor::SearchService::RESULTS_LIMIT = T.let(T.unsafe(nil), Integer)

module SolidQueueMonitor::SortHelper
  def sortable_header(column, label, sort:, filters: T.unsafe(nil)); end

  private

  def sort_arrow(active, direction); end
end

class SolidQueueMonitor::StatsCalculator
  class << self
    def calculate; end
  end
end

class SolidQueueMonitor::StatusCalculator
  def initialize(job); end

  def calculate; end
end

# pkg:gem/solid_queue_monitor#lib/solid_queue_monitor/version.rb:4
SolidQueueMonitor::VERSION = T.let(T.unsafe(nil), String)

module SolidQueueMonitor::WorkersHelper
  def worker_heartbeat(heartbeat_at); end
  def worker_hostname(process); end
  def worker_jobs_processing(process, claimed_counts:, claimed_jobs:); end
  def worker_kind_badge(kind); end
  def worker_metadata(process); end
  def worker_queues(process); end
  def worker_row_class(process); end
  def worker_status(process); end
  def worker_status_badge(status); end
end

SolidQueueMonitor::WorkersHelper::HEARTBEAT_DEAD_THRESHOLD = T.let(T.unsafe(nil), ActiveSupport::Duration)
SolidQueueMonitor::WorkersHelper::HEARTBEAT_STALE_THRESHOLD = T.let(T.unsafe(nil), ActiveSupport::Duration)
