# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `strong_migrations` gem.
# Please instead update this file by running `bin/tapioca gem strong_migrations`.


# note: MariaDB inherits from this adapter
# when making changes, be sure to see how it affects it
# TODO better pattern
#
# pkg:gem/strong_migrations#lib/strong_migrations/adapters/abstract_adapter.rb:1
module StrongMigrations
  class << self
    # pkg:gem/strong_migrations#lib/strong_migrations.rb:68
    def add_check(&block); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def alphabetize_schema; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def alphabetize_schema=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def auto_analyze; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def auto_analyze=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def check_down; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def check_down=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:80
    def check_enabled?(check, version: T.unsafe(nil)); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def checks; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def checks=(_arg0); end

    # private
    #
    # pkg:gem/strong_migrations#lib/strong_migrations.rb:47
    def developer_env?; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:76
    def disable_check(check); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:72
    def enable_check(check, start_after: T.unsafe(nil)); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def enabled_checks; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def enabled_checks=(_arg0); end

    # private
    #
    # pkg:gem/strong_migrations#lib/strong_migrations.rb:52
    def env; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def error_messages; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def error_messages=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def lock_timeout; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def lock_timeout=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:61
    def lock_timeout_limit; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:33
    def lock_timeout_limit=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def lock_timeout_retries; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def lock_timeout_retries=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def lock_timeout_retry_delay; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def lock_timeout_retry_delay=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def remove_invalid_indexes; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def remove_invalid_indexes=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def safe_by_default; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def safe_by_default=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:89
    def skip_database(database); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def skipped_databases; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def skipped_databases=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def start_after; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def start_after=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def statement_timeout; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def statement_timeout=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def target_mariadb_version; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def target_mariadb_version=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def target_mysql_version; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def target_mysql_version=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def target_postgresql_version; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def target_postgresql_version=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def target_sql_mode; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def target_sql_mode=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def target_version; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def target_version=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def transaction_timeout; end

    # pkg:gem/strong_migrations#lib/strong_migrations.rb:28
    def transaction_timeout=(_arg0); end
  end
end

# pkg:gem/strong_migrations#lib/strong_migrations/adapters/abstract_adapter.rb:2
module StrongMigrations::Adapters; end

# pkg:gem/strong_migrations#lib/strong_migrations/adapters/abstract_adapter.rb:3
class StrongMigrations::Adapters::AbstractAdapter
  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/abstract_adapter.rb:4
  def initialize(checker); end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/abstract_adapter.rb:31
  def add_column_default_safe?; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/abstract_adapter.rb:43
  def auto_incrementing_types; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/abstract_adapter.rb:35
  def change_type_safe?(table, column, type, options, existing_column, existing_type); end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/abstract_adapter.rb:27
  def check_lock_timeout(limit); end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/abstract_adapter.rb:47
  def max_constraint_name_length; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/abstract_adapter.rb:12
  def min_version; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/abstract_adapter.rb:8
  def name; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/abstract_adapter.rb:39
  def rewrite_blocks; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/abstract_adapter.rb:23
  def set_lock_timeout(timeout); end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/abstract_adapter.rb:15
  def set_statement_timeout(timeout); end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/abstract_adapter.rb:19
  def set_transaction_timeout(timeout); end

  private

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/abstract_adapter.rb:52
  def connection; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/abstract_adapter.rb:56
  def select_all(statement); end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/abstract_adapter.rb:60
  def target_version(target_version); end
end

# pkg:gem/strong_migrations#lib/strong_migrations/adapters/mariadb_adapter.rb:3
class StrongMigrations::Adapters::MariaDBAdapter < ::StrongMigrations::Adapters::MySQLAdapter
  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/mariadb_adapter.rb:27
  def add_column_default_safe?; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/mariadb_adapter.rb:8
  def min_version; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/mariadb_adapter.rb:4
  def name; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/mariadb_adapter.rb:12
  def server_version; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/mariadb_adapter.rb:20
  def set_statement_timeout(timeout); end
end

# pkg:gem/strong_migrations#lib/strong_migrations/adapters/mysql_adapter.rb:5
class StrongMigrations::Adapters::MySQLAdapter < ::StrongMigrations::Adapters::AbstractAdapter
  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/mysql_adapter.rb:46
  def add_column_default_safe?; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/mysql_adapter.rb:42
  def analyze_table(table); end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/mysql_adapter.rb:50
  def change_type_safe?(table, column, type, options, existing_column, existing_type); end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/mysql_adapter.rb:34
  def check_lock_timeout(limit); end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/mysql_adapter.rb:95
  def max_constraint_name_length; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/mysql_adapter.rb:10
  def min_version; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/mysql_adapter.rb:6
  def name; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/mysql_adapter.rb:91
  def rewrite_blocks; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/mysql_adapter.rb:14
  def server_version; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/mysql_adapter.rb:27
  def set_lock_timeout(timeout); end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/mysql_adapter.rb:22
  def set_statement_timeout(timeout); end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/mysql_adapter.rb:86
  def strict_mode?; end

  private

  # do not memoize
  # want latest value
  #
  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/mysql_adapter.rb:103
  def sql_modes; end
end

# pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:3
class StrongMigrations::Adapters::PostgreSQLAdapter < ::StrongMigrations::Adapters::AbstractAdapter
  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:49
  def add_column_default_safe?; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:45
  def analyze_table(table); end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:162
  def auto_incrementing_types; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:53
  def change_type_safe?(table, column, type, options, existing_column, existing_type); end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:35
  def check_lock_timeout(limit); end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:170
  def constraints(table, column); end

  # default to true if unsure
  #
  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:156
  def default_volatile?(default); end

  # only check in non-developer environments (where actual server version is used)
  #
  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:149
  def index_corruption?; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:166
  def max_constraint_name_length; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:8
  def min_version; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:4
  def name; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:12
  def server_version; end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:31
  def set_lock_timeout(timeout); end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:22
  def set_statement_timeout(timeout); end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:26
  def set_transaction_timeout(timeout); end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:135
  def writes_blocked?; end

  private

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:211
  def datetime_type; end

  # columns is array for column index and string for expression index
  # the current approach can yield false positives for expression indexes
  # but prefer to keep it simple for now
  #
  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:207
  def indexed?(table, column); end

  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:177
  def set_timeout(setting, timeout); end

  # do not memoize
  # want latest value
  #
  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:222
  def time_zone; end

  # units: https://www.postgresql.org/docs/current/config-setting.html
  #
  # pkg:gem/strong_migrations#lib/strong_migrations/adapters/postgresql_adapter.rb:185
  def timeout_to_sec(timeout); end
end

# pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:2
class StrongMigrations::Checker
  include ::StrongMigrations::Checks
  include ::StrongMigrations::SafeMethods

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:12
  def initialize(migration); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:6
  def direction; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:6
  def direction=(_arg0); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:36
  def perform(method, *args, &block); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:125
  def perform_method(method, *args); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:17
  def reset; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:132
  def retry_lock_timeouts(check_committed: T.unsafe(nil)); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:156
  def set_transaction_timeout; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:152
  def skip?; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:6
  def timeouts_set; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:6
  def timeouts_set=(_arg0); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:6
  def transaction_disabled; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:6
  def transaction_disabled=(_arg0); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:148
  def version_safe?; end

  private

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:223
  def adapter; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:270
  def adds_index?(method, *args); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:168
  def check_adapter; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:205
  def check_lock_timeout; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:178
  def check_version_supported; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:243
  def connection; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:247
  def db_config_name; end

  # REINDEX INDEX CONCURRENTLY leaves a new invalid index if it fails, so use remove_index instead
  #
  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:283
  def remove_invalid_index_if_needed(*args); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:251
  def retry_lock_timeouts?(method); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:215
  def safe?; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:192
  def set_timeouts; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:219
  def version; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:260
  def without_retries; end

  class << self
    # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:9
    def safe; end

    # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:9
    def safe=(_arg0); end

    # pkg:gem/strong_migrations#lib/strong_migrations/checker.rb:26
    def safety_assured; end
  end
end

# pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:3
module StrongMigrations::Checks
  private

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:512
  def ar_version; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:578
  def backfill_code(table, column, default, function = T.unsafe(nil)); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:6
  def check_add_check_constraint(*args); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:30
  def check_add_column(*args); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:96
  def check_add_exclusion_constraint(*args); end

  # unlike add_index, we don't make an exception here for new tables
  #
  # with add_index, it's fine to lock a new table even after inserting data
  # since the table won't be in use by the application
  #
  # with add_foreign_key, this would cause issues since it locks the referenced table
  #
  # it's okay to allow if the table is empty, but not a fan of data-dependent checks,
  # since the data in production could be different from development
  #
  # note: adding foreign_keys with create_table is fine
  # since the table is always guaranteed to be empty
  #
  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:116
  def check_add_foreign_key(*args); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:138
  def check_add_index(*args); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:167
  def check_add_reference(method, *args); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:250
  def check_add_unique_constraint(*args); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:531
  def check_algorithm_option(method, *args, **options); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:265
  def check_change_column(*args); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:317
  def check_change_column_default(*args); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:329
  def check_change_column_null(*args); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:385
  def check_change_table; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:389
  def check_create_join_table(*args); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:397
  def check_create_table(*args); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:407
  def check_execute; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:537
  def check_lock_option(method, *args, **options); end

  # supports algorithm and lock options, but always raises
  #
  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:412
  def check_remove_column(method, *args); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:443
  def check_remove_index(*args); end

  # supports algorithm and lock options, but always raises
  #
  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:466
  def check_rename_column; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:470
  def check_rename_enum_value(*args); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:478
  def check_rename_schema; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:482
  def check_rename_table; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:486
  def check_validate_check_constraint; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:492
  def check_validate_foreign_key; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:555
  def command_str(command, args); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:546
  def constraint_str(statement, identifiers); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:508
  def mariadb?; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:603
  def migration_suffix; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:607
  def model_name(table); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:504
  def mysql?; end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:599
  def new_column?(table, column); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:595
  def new_table?(table); end

  # helpers
  #
  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:500
  def postgresql?; end

  # only quote when needed
  # important! only use for display purposes
  #
  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:591
  def quote_column_if_needed(column); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:516
  def raise_error(message_key, header: T.unsafe(nil), append: T.unsafe(nil), **vars); end

  # pkg:gem/strong_migrations#lib/strong_migrations/checks.rb:551
  def safety_assured_str(code); end
end

# pkg:gem/strong_migrations#lib/strong_migrations.rb:23
class StrongMigrations::Error < ::StandardError; end

# pkg:gem/strong_migrations#lib/strong_migrations/migration.rb:2
module StrongMigrations::Migration
  # pkg:gem/strong_migrations#lib/strong_migrations/migration.rb:9
  def method_missing(method, *args, **_arg2); end

  # pkg:gem/strong_migrations#lib/strong_migrations/migration.rb:3
  def migrate(direction); end

  # pkg:gem/strong_migrations#lib/strong_migrations/migration.rb:21
  def revert(*_arg0); end

  # pkg:gem/strong_migrations#lib/strong_migrations/migration.rb:29
  def safety_assured; end

  # pkg:gem/strong_migrations#lib/strong_migrations/migration.rb:35
  def stop!(message, header: T.unsafe(nil)); end

  private

  # pkg:gem/strong_migrations#lib/strong_migrations/migration.rb:41
  def strong_migrations_checker; end
end

# pkg:gem/strong_migrations#lib/strong_migrations/migration_context.rb:2
module StrongMigrations::MigrationContext
  # pkg:gem/strong_migrations#lib/strong_migrations/migration_context.rb:9
  def down(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/strong_migrations#lib/strong_migrations/migration_context.rb:15
  def run(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/strong_migrations#lib/strong_migrations/migration_context.rb:3
  def up(*_arg0, **_arg1, &_arg2); end

  private

  # pkg:gem/strong_migrations#lib/strong_migrations/migration_context.rb:23
  def strong_migrations_process_exception(e); end
end

# pkg:gem/strong_migrations#lib/strong_migrations/migrator.rb:2
module StrongMigrations::Migrator
  # pkg:gem/strong_migrations#lib/strong_migrations/migrator.rb:3
  def ddl_transaction(migration, *_arg1, **_arg2, &_arg3); end
end

# pkg:gem/strong_migrations#lib/strong_migrations/railtie.rb:5
class StrongMigrations::Railtie < ::Rails::Railtie; end

# pkg:gem/strong_migrations#lib/strong_migrations/safe_methods.rb:2
module StrongMigrations::SafeMethods
  # hard to commit at right time when reverting
  # so just commit at start
  #
  # pkg:gem/strong_migrations#lib/strong_migrations/safe_methods.rb:137
  def disable_transaction; end

  # pkg:gem/strong_migrations#lib/strong_migrations/safe_methods.rb:144
  def in_transaction?; end

  # pkg:gem/strong_migrations#lib/strong_migrations/safe_methods.rb:61
  def safe_add_check_constraint(table, expression, *args, add_options, validate_options); end

  # pkg:gem/strong_migrations#lib/strong_migrations/safe_methods.rb:46
  def safe_add_foreign_key(from_table, to_table, *args, **options); end

  # pkg:gem/strong_migrations#lib/strong_migrations/safe_methods.rb:7
  def safe_add_index(*args, **options); end

  # pkg:gem/strong_migrations#lib/strong_migrations/safe_methods.rb:17
  def safe_add_reference(table, reference, *args, **options); end

  # pkg:gem/strong_migrations#lib/strong_migrations/safe_methods.rb:3
  def safe_by_default_method?(method); end

  # pkg:gem/strong_migrations#lib/strong_migrations/safe_methods.rb:77
  def safe_change_column_null(add_args, validate_args, change_args, remove_args, table, column, default, constraints); end

  # pkg:gem/strong_migrations#lib/strong_migrations/safe_methods.rb:12
  def safe_remove_index(*args, **options); end
end

# pkg:gem/strong_migrations#lib/strong_migrations/schema_dumper.rb:2
module StrongMigrations::SchemaDumper
  # pkg:gem/strong_migrations#lib/strong_migrations/schema_dumper.rb:3
  def initialize(connection, *_arg1, **_arg2, &_arg3); end
end

# pkg:gem/strong_migrations#lib/strong_migrations.rb:24
class StrongMigrations::UnsafeMigration < ::StrongMigrations::Error; end

# pkg:gem/strong_migrations#lib/strong_migrations.rb:25
class StrongMigrations::UnsupportedVersion < ::StrongMigrations::Error; end

# pkg:gem/strong_migrations#lib/strong_migrations/version.rb:2
StrongMigrations::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/strong_migrations#lib/strong_migrations/schema_dumper.rb:10
class StrongMigrations::WrappedConnection
  # pkg:gem/strong_migrations#lib/strong_migrations/schema_dumper.rb:13
  def initialize(connection); end

  # pkg:gem/strong_migrations#lib/strong_migrations/schema_dumper.rb:17
  def columns(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/strong_migrations#lib/strong_migrations/schema_dumper.rb:11
  def method_missing(method, *_arg1, **_arg2, &_arg3); end

  # forward private methods with send
  # method_missing cannot tell how method was called
  # this is not ideal, but other solutions have drawbacks
  #
  # pkg:gem/strong_migrations#lib/strong_migrations/schema_dumper.rb:24
  def send(name, *_arg1, **_arg2, &_arg3); end

  private

  # pkg:gem/strong_migrations#lib/strong_migrations/schema_dumper.rb:11
  def respond_to_missing?(name, include_private = T.unsafe(nil)); end
end
