// Typelizer digest 0936d0ae9bc8e5fc7add0767d854e763
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Language = {
  id: number;
  description: string | null;
  locale: string | null;
  created_at: string;
  state: string | null;
  order: number | null;
  duration: string | null;
  members_count: number | null;
  slug: string | null;
  title: string | null;
  name: string | null;
  cover: string | null;
}

export default Language;
