// Typelizer digest 3f6504199a8633b26213c5eed3ba08f2
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {LanguageCategoryItem} from '@/types'

type LanguageCategoryCrudData = {
  id: number;
  slug: string | null;
  name: string | null;
  header: string | null;
  description: string | null;
  items: Array<LanguageCategoryItem>;
}

type LanguageCategoryCrud = {
  language_category: LanguageCategoryCrudData;
  meta: { landingPagesForCategories: LanguageCategoryCrudData[] };
}

export default LanguageCategoryCrud;
