// Typelizer digest 1593341bc68001988af49e05aecc31d5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Locale} from '@/types'

type LanguageOriginalLesson = {
  language: Locale | null;
  id: number;
  slug: string | null;
  language_id: number | null;
  module_id: number | null;
  created_at: string;
}

export default LanguageOriginalLesson;
