// Typelizer digest f7caca6b8737ef9a89cc8e99135a46c4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Lead = {
  id: number;
  user_id: number;
  phone: string | null;
  whatsapp: string | null;
  telegram: string | null;
  survey_answers_data: string | null;
  full_name: string | null;
  email: string | null;
}

export default Lead;
