// Typelizer digest 07da010b0af151ff66e05e0cde5e0540
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PasswordReminder = {
  email: unknown;
}

export default PasswordReminder;
