// Typelizer digest dde9deb9d5f58ff25424787460ce896e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {User, Language, ReviewState, ReviewLocale} from '@/types'

type Review = {
  user: User;
  language: Language;
  id: number;
  body: string | null;
  state: ReviewState | null;
  first_name: string | null;
  last_name: string | null;
  language_id: number;
  user_id: number;
  created_at: string;
  locale: ReviewLocale | null;
  full_name: string | null;
}

export default Review;
