// Typelizer digest 488830db70d99ec06af9d7576cb283b2
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {SurveyScenarioItemCrudResourceMeta} from '@/types'

type SurveyScenarioItemCrud = {
  id: number | null;
  survey_id: number | null;
  order: number | null;
  _destroy: boolean;
  meta: SurveyScenarioItemCrudResourceMeta;
}

export default SurveyScenarioItemCrud;
