// Typelizer digest b4567dfb5762b6c61442ea6b9c28d077
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type User = {
  id: number;
  first_name: string | null;
  email: string | null;
  created_at: string;
  last_name: string | null;
  admin: boolean | null;
  assistant_messages_count: number | null;
  guest: boolean | null;
  name: string | null;
  password: string | null;
  created_at_as_timestamp: number | null;
  type: "user";
}

export default User;
