// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package apiconv

import (
	ent "hexletbasics/ent"
	api "hexletbasics/internal/api"
)

type ConverterImpl struct{}

func (c *ConverterImpl) ToCatalogItem(source *ent.LandingPage) api.CourseCatalogItem {
	var apiCourseCatalogItem api.CourseCatalogItem
	if source != nil {
		apiCourseCatalogItem.ID = Int32FromInt((*source).ID)
		apiCourseCatalogItem.Slug = StringFromPtr((*source).Slug)
		apiCourseCatalogItem.Header = NilStringFromPtr((*source).Header)
		apiCourseCatalogItem.Name = NilStringFromPtr((*source).Name)
		apiCourseCatalogItem.Locale = NilStringFromPtr((*source).Locale)
		var pInt *int
		if (*source).Edges.Course != nil {
			pInt = &(*source).Edges.Course.MembersCount
		}
		if pInt != nil {
			apiCourseCatalogItem.MembersCount = Int32FromInt(*pInt)
		}
		apiCourseCatalogItem.CoverUrl = coverURLNull(source)
		apiCourseCatalogItem.Course = c.ToCourse((*source).Edges.Course)
	}
	return apiCourseCatalogItem
}
func (c *ConverterImpl) ToCatalogItems(source []*ent.LandingPage) []api.CourseCatalogItem {
	var apiCourseCatalogItemList []api.CourseCatalogItem
	if source != nil {
		apiCourseCatalogItemList = make([]api.CourseCatalogItem, len(source))
		for i := 0; i < len(source); i++ {
			apiCourseCatalogItemList[i] = c.ToCatalogItem(source[i])
		}
	}
	return apiCourseCatalogItemList
}
func (c *ConverterImpl) ToCourse(source *ent.Course) api.Course {
	var apiCourse api.Course
	if source != nil {
		apiCourse.ID = Int32FromInt((*source).ID)
		apiCourse.Slug = StringFromPtr((*source).Slug)
		apiCourse.Name = NilStringFromPtr((*source).Name)
		apiCourse.LearnAs = NilLearnAsFromPtr((*source).LearnAs)
		apiCourse.Progress = NilProgressFromPtr((*source).Progress)
		apiCourse.MembersCount = Int32FromInt((*source).MembersCount)
		apiCourse.LessonsCount = Int32FromInt((*source).LessonsCount)
		apiCourse.CategoryId = NilInt32FromPtr((*source).CategoryID)
	}
	return apiCourse
}
