// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ActiveStorageAttachment is the predicate function for activestorageattachment builders.
type ActiveStorageAttachment func(*sql.Selector)

// ActiveStorageBlob is the predicate function for activestorageblob builders.
type ActiveStorageBlob func(*sql.Selector)

// AiChat is the predicate function for aichat builders.
type AiChat func(*sql.Selector)

// AiMessage is the predicate function for aimessage builders.
type AiMessage func(*sql.Selector)

// Attachment is the predicate function for attachment builders.
type Attachment func(*sql.Selector)

// Banner is the predicate function for banner builders.
type Banner func(*sql.Selector)

// BlogPost is the predicate function for blogpost builders.
type BlogPost func(*sql.Selector)

// BlogPostLike is the predicate function for blogpostlike builders.
type BlogPostLike func(*sql.Selector)

// BlogPostRelatedCourseItem is the predicate function for blogpostrelatedcourseitem builders.
type BlogPostRelatedCourseItem func(*sql.Selector)

// CategoryQnaItem is the predicate function for categoryqnaitem builders.
type CategoryQnaItem func(*sql.Selector)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// CourseCategory is the predicate function for coursecategory builders.
type CourseCategory func(*sql.Selector)

// CourseLesson is the predicate function for courselesson builders.
type CourseLesson func(*sql.Selector)

// CourseLessonReview is the predicate function for courselessonreview builders.
type CourseLessonReview func(*sql.Selector)

// CourseLessonTranslation is the predicate function for courselessontranslation builders.
type CourseLessonTranslation func(*sql.Selector)

// CourseLessonVersion is the predicate function for courselessonversion builders.
type CourseLessonVersion func(*sql.Selector)

// CourseModule is the predicate function for coursemodule builders.
type CourseModule func(*sql.Selector)

// CourseModuleTranslation is the predicate function for coursemoduletranslation builders.
type CourseModuleTranslation func(*sql.Selector)

// CourseModuleVersion is the predicate function for coursemoduleversion builders.
type CourseModuleVersion func(*sql.Selector)

// CourseVersion is the predicate function for courseversion builders.
type CourseVersion func(*sql.Selector)

// LandingPage is the predicate function for landingpage builders.
type LandingPage func(*sql.Selector)

// LandingPageQnaItem is the predicate function for landingpageqnaitem builders.
type LandingPageQnaItem func(*sql.Selector)

// Lead is the predicate function for lead builders.
type Lead func(*sql.Selector)

// LessonProgress is the predicate function for lessonprogress builders.
type LessonProgress func(*sql.Selector)

// Review is the predicate function for review builders.
type Review func(*sql.Selector)

// StaffMember is the predicate function for staffmember builders.
type StaffMember func(*sql.Selector)

// StaffRole is the predicate function for staffrole builders.
type StaffRole func(*sql.Selector)

// StaffRolePermission is the predicate function for staffrolepermission builders.
type StaffRolePermission func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
